export type DuaSection = 'ramadan' | 'masnoon';

export type DuaGroup =
  | 'ramadan' | 'daily' | 'prayer' | 'home' | 'food'
  | 'health' | 'social' | 'hajj' | 'protection' | 'forgiveness' | 'special';

export interface Dua {
  id: string;
  group: DuaGroup;
  title: string;
  arabic: string;
  transliteration: string;
  english: string;
  reference: string;
  tags?: string[];
}

export const DUA_GROUP_LABELS: Record<DuaGroup, string> = {
  ramadan:    'Ramadan Duas',
  daily:      'Daily Remembrance',
  prayer:     'Prayer Duas',
  home:       'Home & Travel',
  food:       'Food & Drink',
  health:     'Health & Wellbeing',
  social:     'Social & Gatherings',
  hajj:       'Hajj & Umrah',
  protection: 'Protection & Safety',
  forgiveness:'Forgiveness & Repentance',
  special:    'Special Occasions',
};

export const DUAS: Dua[] = [
  // ── RAMADAN DUAS ──────────────────────────────────────────────────────────
  {
    id: 'ramadan-moon',
    group: 'ramadan',
    title: 'For Ramadan Moon Sighting',
    arabic: 'اللَّهُ أَكْبَرُ، اللَّهُمَّ أَهِلَّهُ عَلَيْنَا بِالْأَمْنِ وَالْإِيمَانِ، وَالسَّلَامَةِ وَالْإِسْلَامِ، وَالتَّوْفِيقِ لِمَا تُحِبُّ وَتَرْضَى، رَبُّنَا وَرَبُّكَ اللَّهُ',
    transliteration: 'Allahu Akbar, Allahumma ahillahu alayna bil amni wal iman, was-salamati wal-Islam, wat-tawfiqi lima tuhibbu wa tardha, Rabbuna wa Rabbuka Allah.',
    english: 'Allah is the Greatest. O Allah, bring it (the crescent) upon us with blessing, faith, safety and Islam, and with agreement to do what You love and are pleased with. Our Lord and your Lord is Allah.',
    reference: 'Tirmidhi 3451',
    tags: ['ramadan', 'moon', 'crescent'],
  },
  {
    id: 'sehri',
    group: 'ramadan',
    title: 'For Fasting – Sehri (Niyyah)',
    arabic: 'وَبِصَوْمِ غَدٍ نَّوَيْتُ مِنْ شَهْرِ رَمَضَانَ',
    transliteration: 'Wa bisawmi ghadin nawaytu min shahri Ramadan.',
    english: 'I intend to keep the fast of tomorrow in the month of Ramadan.',
    reference: 'Abu Dawood (Niyyah for fasting)',
    tags: ['sehri', 'fast', 'niyyah'],
  },
  {
    id: 'iftar',
    group: 'ramadan',
    title: 'For Breaking Fast – Iftar Dua',
    arabic: 'اللَّهُمَّ لَكَ صُمْتُ وَعَلَى رِزْقِكَ أَفْطَرْتُ',
    transliteration: "Allahumma laka sumtu wa 'ala rizqika aftartu.",
    english: 'O Allah, for You I fasted and with Your provisions I break my fast.',
    reference: 'Abu Dawood 2358',
    tags: ['iftar', 'fast', 'breaking'],
  },
  {
    id: 'iftar-thirst',
    group: 'ramadan',
    title: 'Iftar – Dua after breaking fast',
    arabic: 'ذَهَبَ الظَّمَأُ وَابْتَلَّتِ الْعُرُوقُ وَثَبَتَ الْأَجْرُ إِنْ شَاءَ اللَّهُ',
    transliteration: "Dhahaba-z-zama'u wab-tallatil 'uruqu wa thabatal ajru insha Allah.",
    english: 'The thirst has gone, the veins are moistened, and the reward is confirmed, if Allah wills.',
    reference: 'Abu Dawood 2357',
    tags: ['iftar', 'fast'],
  },
  {
    id: 'iftar-provider',
    group: 'ramadan',
    title: 'For Someone who provides you Iftar',
    arabic: 'أَفْطَرَ عِنْدَكُمُ الصَّائِمُونَ وَأَكَلَ طَعَامَكُمُ الْأَبْرَارُ وَصَلَّتْ عَلَيْكُمُ الْمَلَائِكَةُ',
    transliteration: "Aftara 'indakumus sa'imuna wa akala ta'amakumul abraru wa sallat 'alaykumul mala'ikah.",
    english: 'May the fasting people break their fast with you, may the pious eat your food, and may the angels pray for you.',
    reference: 'Abu Dawood 3854, Ibn Majah 1747',
    tags: ['iftar', 'host', 'blessing'],
  },
  {
    id: 'ashra-1',
    group: 'ramadan',
    title: '1st Ashra Dua (First 10 Days)',
    arabic: 'يَا حَيُّ يَا قَيُّومُ بِرَحْمَتِكَ أَسْتَغِيثُ',
    transliteration: 'Ya Hayyu ya Qayyumu birahmatika astagheeth.',
    english: 'O the Living, O the Self-Sustaining, by Your mercy I seek help.',
    reference: 'Tirmidhi 3524 (authenticated)',
    tags: ['ashra', 'ramadan', 'mercy'],
  },
  {
    id: 'ashra-2',
    group: 'ramadan',
    title: '2nd Ashra Dua (Middle 10 Days)',
    arabic: 'أَسْتَغْفِرُ اللَّهَ رَبِّي مِنْ كُلِّ ذَنْبٍ وَأَتُوبُ إِلَيْهِ',
    transliteration: "Astaghfirullaha Rabbi min kulli dhanbin wa atubu ilayh.",
    english: 'I seek forgiveness of Allah, my Lord, from every sin and I turn to Him in repentance.',
    reference: 'Authenticated supplications for forgiveness',
    tags: ['ashra', 'forgiveness', 'ramadan'],
  },
  {
    id: 'ashra-3',
    group: 'ramadan',
    title: '3rd Ashra Dua (Last 10 Days)',
    arabic: 'اللَّهُمَّ أَجِرْنِي مِنَ النَّارِ',
    transliteration: 'Allahumma ajirni minan-nar.',
    english: 'O Allah, save me from the Fire.',
    reference: 'Abu Dawood, Ibn Majah',
    tags: ['ashra', 'hellfire', 'protection', 'ramadan'],
  },
  {
    id: 'laylatul-qadr',
    group: 'ramadan',
    title: 'For Laylatul Qadr (Night of Decree)',
    arabic: 'اللَّهُمَّ إِنَّكَ عَفُوٌّ تُحِبُّ الْعَفْوَ فَاعْفُ عَنِّي',
    transliteration: "Allahumma innaka 'afuwwun tuhibbul 'afwa fa'fu 'anni.",
    english: 'O Allah, You are the Pardoning and You love to pardon, so pardon me.',
    reference: 'Tirmidhi 3513 – Aisha (RA) asked the Prophet (SAW) this dua',
    tags: ['laylatul qadr', 'night of decree', 'ramadan', 'forgiveness'],
  },

  // ── DAILY DUAS ────────────────────────────────────────────────────────────
  {
    id: 'waking-up',
    group: 'daily',
    title: 'When Waking Up',
    arabic: 'الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ',
    transliteration: 'Alhamdu lillahil-ladhi ahyana ba`da ma amatana wa ilayhin-nushur.',
    english: 'All praise is for Allah who gave us life after causing us to die, and to Him is the return.',
    reference: 'Bukhari 6312, Muslim 2711',
    tags: ['morning', 'waking', 'daily'],
  },
  {
    id: 'before-sleep',
    group: 'daily',
    title: 'Before Sleeping',
    arabic: 'اللَّهُمَّ بِاسْمِكَ أَمُوتُ وَأَحْيَا',
    transliteration: 'Allahumma bismika amutu wa ahya.',
    english: 'O Allah, in Your name I die and I live.',
    reference: 'Bukhari 6324',
    tags: ['night', 'sleep', 'daily'],
  },
  {
    id: 'morning-remembrance',
    group: 'daily',
    title: 'Morning Remembrance (Subh ka Azkar)',
    arabic: 'أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ',
    transliteration: "Asbahna wa asbahal mulku lillah, wal hamdu lillah, la ilaha illallahu wahdahu la sharika lah, lahul mulku wa lahul hamdu wa huwa 'ala kulli shay'in qadir.",
    english: 'We have entered the morning and the whole kingdom of Allah has entered the morning. Praise is for Allah. None has the right to be worshipped except Allah alone, with no partner, His is the dominion and His is the praise, and He is over all things competent.',
    reference: 'Muslim 2723',
    tags: ['morning', 'azkar'],
  },
  {
    id: 'evening-remembrance',
    group: 'daily',
    title: 'Evening Remembrance (Shaam ka Azkar)',
    arabic: 'أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ',
    transliteration: 'Amsayna wa amsal mulku lillah, walhamdu lillah, la ilaha illallahu wahdahu la sharika lah.',
    english: 'We have entered the evening and the whole kingdom of Allah has entered the evening. Praise is for Allah. None has the right to be worshipped except Allah alone, with no partner.',
    reference: 'Muslim 2723',
    tags: ['evening', 'azkar'],
  },
  {
    id: 'after-rainfall',
    group: 'daily',
    title: 'After Rainfall',
    arabic: 'مُطِرْنَا بِفَضْلِ اللَّهِ وَرَحْمَتِهِ',
    transliteration: "Mutirna bifadlillahi wa rahmatih.",
    english: 'It has rained by the grace and mercy of Allah.',
    reference: 'Bukhari 846, Muslim 71',
    tags: ['rain', 'weather'],
  },
  {
    id: 'during-windstorm',
    group: 'daily',
    title: 'During a Windstorm',
    arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ خَيْرَهَا وَخَيْرَ مَا فِيهَا وَخَيْرَ مَا أُرْسِلَتْ بِهِ وَأَعُوذُ بِكَ مِنْ شَرِّهَا وَشَرِّ مَا فِيهَا وَشَرِّ مَا أُرْسِلَتْ بِهِ',
    transliteration: 'Allahumma inni as-aluka khayraha wa khayra ma fiha wa khayra ma ursilat bih, wa a`udhu bika min sharriha wa sharri ma fiha wa sharri ma ursilat bih.',
    english: 'O Allah, I ask You for the good of it, the good within it, and the good it was sent with. And I seek refuge in You from the evil of it, the evil within it, and the evil it was sent with.',
    reference: 'Muslim 899',
    tags: ['wind', 'storm', 'weather'],
  },
  {
    id: 'upon-hearing-thunder',
    group: 'daily',
    title: 'Upon Hearing Thunder',
    arabic: 'سُبْحَانَ الَّذِي يُسَبِّحُ الرَّعْدُ بِحَمْدِهِ وَالْمَلَائِكَةُ مِنْ خِيفَتِهِ',
    transliteration: 'Subhanal-ladhi yusabbihur-ra`du bihamdihi wal mala-ikatu min khifatih.',
    english: 'Glory be to the One whom the thunder glorifies with His praises, as do the angels in awe of Him.',
    reference: 'Muwatta Malik 3:18, Tirmidhi',
    tags: ['thunder', 'weather'],
  },
  {
    id: 'for-rain',
    group: 'daily',
    title: 'Supplication for Rain (Istisqa)',
    arabic: 'اللَّهُمَّ اسْقِنَا غَيْثًا مُغِيثًا مَرِيئًا مَرِيعًا نَافِعًا غَيْرَ ضَارٍّ عَاجِلًا غَيْرَ آجِلٍ',
    transliteration: "Allahummasqina ghaysan mughithan mari-an mari`an nafi`an ghayra dharrin `ajilan ghayra ajil.",
    english: 'O Allah, give us rain that is helpful and beneficial, pleasant and wholesome, soon and not delayed.',
    reference: 'Abu Dawood 1169',
    tags: ['rain', 'istisqa', 'dua'],
  },
  {
    id: 'in-times-happiness',
    group: 'daily',
    title: 'In Times of Happiness',
    arabic: 'الْحَمْدُ لِلَّهِ الَّذِي بِنِعْمَتِهِ تَتِمُّ الصَّالِحَاتُ',
    transliteration: 'Alhamdu lillahil-ladhi bini`matihi tatimmus-salihat.',
    english: 'All praise is for Allah, by whose grace good deeds are completed.',
    reference: 'Ibn Majah 3803',
    tags: ['happiness', 'gratitude'],
  },
  {
    id: 'at-times-worry',
    group: 'daily',
    title: 'At Times of Worry and Sorrow',
    arabic: 'اللَّهُمَّ إِنِّي عَبْدُكَ ابْنُ عَبْدِكَ ابْنُ أَمَتِكَ نَاصِيَتِي بِيَدِكَ مَاضٍ فِيَّ حُكْمُكَ عَدْلٌ فِيَّ قَضَاؤُكَ أَسْأَلُكَ بِكُلِّ اسْمٍ هُوَ لَكَ سَمَّيْتَ بِهِ نَفْسَكَ أَوْ أَنْزَلْتَهُ فِي كِتَابِكَ أَوْ عَلَّمْتَهُ أَحَدًا مِنْ خَلْقِكَ أَوِ اسْتَأْثَرْتَ بِهِ فِي عِلْمِ الْغَيْبِ عِنْدَكَ أَنْ تَجْعَلَ الْقُرْآنَ رَبِيعَ قَلْبِي وَنُورَ صَدْرِي وَجِلَاءَ حُزْنِي وَذَهَابَ هَمِّي',
    transliteration: "Allahumma inni `abduka ibnu `abdika ibnu amatika nasiyati biyadika, madin fiyya hukmuka, `adlun fiyya qada-uka, as-aluka bikulli ismin huwa laka sammayta bihi nafsaka aw anzaltahu fi kitabika aw `allamtahu ahadan min khalqika awista-tharta bihi fi `ilmil ghaybi `indaka an taj`alal qurana rabi`a qalbi wa nura sadri wa jila-a huzni wa dhahaba hammi.",
    english: 'O Allah, I am Your servant, son of Your servant, son of Your female servant. My forelock is in Your Hand, Your command over me is forever executed, and Your decree over me is just. I ask You by every name belonging to You which You have named Yourself with, or which You have taught to any of Your creation, or which You have preserved in Your knowledge of the unseen — to make the Quran the spring of my heart, the light of my chest, the departure of my sorrow and the end of my anxiety.',
    reference: 'Ahmad 3704 – Authenticated',
    tags: ['worry', 'sorrow', 'anxiety', 'quran'],
  },
  {
    id: 'on-bad-news',
    group: 'daily',
    title: 'On Hearing Bad News',
    arabic: 'إِنَّا لِلَّهِ وَإِنَّا إِلَيْهِ رَاجِعُونَ، اللَّهُمَّ أْجُرْنِي فِي مُصِيبَتِي وَأَخْلِفْ لِي خَيْرًا مِنْهَا',
    transliteration: "Inna lillahi wa inna ilayhi raji`un, Allahumma-jurni fi musibati wa akhlif li khayran minha.",
    english: 'Verily we belong to Allah, and indeed to Him we shall return. O Allah, reward me for my affliction and replace it for me with something better.',
    reference: 'Muslim 918',
    tags: ['loss', 'tragedy', 'patience'],
  },
  {
    id: 'on-good-news',
    group: 'daily',
    title: 'On Hearing Good News',
    arabic: 'الْحَمْدُ لِلَّهِ الَّذِي بِنِعْمَتِهِ تَتِمُّ الصَّالِحَاتُ',
    transliteration: 'Alhamdu lillahil-ladhi bini`matihi tatimmus-salihat.',
    english: 'All praise is for Allah, by whose grace and blessings good deeds are completed.',
    reference: 'Ibn Majah 3803',
    tags: ['good news', 'gratitude'],
  },
  {
    id: 'when-loss',
    group: 'daily',
    title: 'When a Loss Occurs',
    arabic: 'إِنَّا لِلَّهِ وَإِنَّا إِلَيْهِ رَاجِعُونَ',
    transliteration: 'Inna lillahi wa inna ilayhi raji`un.',
    english: 'Verily we belong to Allah, and indeed to Him we shall return.',
    reference: 'Quran 2:156 (Al-Baqarah)',
    tags: ['loss', 'inna lillahi', 'patience'],
  },
  {
    id: 'when-distress',
    group: 'daily',
    title: 'When in Distress',
    arabic: 'لَا إِلَهَ إِلَّا أَنتَ سُبْحَانَكَ إِنِّي كُنتُ مِنَ الظَّالِمِينَ',
    transliteration: 'La ilaha illa anta subhanaka inni kuntu minaz-zalimin.',
    english: 'There is no deity except You; exalted are You. Indeed, I have been of the wrongdoers.',
    reference: 'Quran 21:87 – Dua of Yunus (AS)',
    tags: ['distress', 'yunus', 'tawbah'],
  },
  {
    id: 'when-frightened',
    group: 'daily',
    title: 'When Feeling Frightened',
    arabic: 'أَعُوذُ بِكَلِمَاتِ اللَّهِ التَّامَّاتِ مِنْ غَضَبِهِ وَعِقَابِهِ وَشَرِّ عِبَادِهِ وَمِنْ هَمَزَاتِ الشَّيَاطِينِ وَأَنْ يَحْضُرُونِ',
    transliteration: "A`udhu bikalimatillahit-tammati min ghadabihi wa `iqabihi wa sharri `ibadihi wa min hamazatish-shayatini wa an yahdurun.",
    english: 'I seek refuge in the perfect words of Allah from His anger, His punishment, the evil of His servants, and from the whisperings of the devils and their presence.',
    reference: 'Abu Dawood 3893, Tirmidhi 3528',
    tags: ['fear', 'protection', 'shaitan'],
  },
  {
    id: 'stricken-by-tragedy',
    group: 'daily',
    title: 'When Stricken by Tragedy',
    arabic: 'اللَّهُمَّ اغْفِرْ لَنَا وَارْحَمْنَا، اللَّهُمَّ أَجِرْنَا مِنَ النَّارِ',
    transliteration: "Allahummaghfir lana warhamna, Allahumma ajirna minan-nar.",
    english: 'O Allah, forgive us and have mercy on us. O Allah, protect us from the Fire.',
    reference: 'Authenticated supplication',
    tags: ['tragedy', 'difficulty', 'mercy'],
  },
  {
    id: 'increase-knowledge',
    group: 'daily',
    title: 'Increase in Knowledge',
    arabic: 'رَّبِّ زِدْنِي عِلْمًا',
    transliteration: "Rabbi zidni `ilma.",
    english: 'My Lord, increase me in knowledge.',
    reference: 'Quran 20:114 (Ta-Ha)',
    tags: ['knowledge', 'ilm', 'learning'],
  },
  {
    id: 'looking-in-mirror',
    group: 'daily',
    title: 'When Looking into the Mirror',
    arabic: 'اللَّهُمَّ أَنْتَ حَسَّنْتَ خَلْقِي فَحَسِّنْ خُلُقِي',
    transliteration: "Allahumma anta hassanta khalqi fahassin khuluqi.",
    english: 'O Allah, just as You have made my external features beautiful, make my character beautiful as well.',
    reference: 'Ahmad 3748',
    tags: ['mirror', 'character', 'daily'],
  },
  {
    id: 'pledge-to-allah',
    group: 'daily',
    title: 'Pledge to Allah (Sayyidul Istighfar)',
    arabic: 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ خَلَقْتَنِي وَأَنَا عَبْدُكَ وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ',
    transliteration: "Allahumma anta Rabbi la ilaha illa anta, khalaqtani wa ana `abduka, wa ana `ala `ahdika wa wa`dika mastata`tu, a`udhu bika min sharri ma sana`tu, abu-u laka bini`matika `alayya wa abu-u bidhanbi, faghfir li fa-innahu la yaghfirudh-dhunuba illa anta.",
    english: 'O Allah, You are my Lord. None has the right to be worshipped except You. You created me and I am Your servant, and I am under Your covenant and pledge as much as I am able. I seek refuge in You from the evil of what I have done. I acknowledge Your blessing upon me, and I acknowledge my sin, so forgive me, for none forgives sins except You.',
    reference: 'Bukhari 6306 – Sayyidul Istighfar',
    tags: ['forgiveness', 'istighfar', 'pledge'],
  },

  // ── PRAYER DUAS ───────────────────────────────────────────────────────────
  {
    id: 'darood-ibrahimi',
    group: 'prayer',
    title: 'Darood-e-Ibrahimi',
    arabic: 'اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ كَمَا صَلَّيْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ إِنَّكَ حَمِيدٌ مَجِيدٌ، اللَّهُمَّ بَارِكْ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ كَمَا بَارَكْتَ عَلَى إِبْرَاهِيمَ وَعَلَى آلِ إِبْرَاهِيمَ إِنَّكَ حَمِيدٌ مَجِيدٌ',
    transliteration: "Allahumma salli `ala Muhammadin wa `ala ali Muhammadin kama sallayta `ala Ibrahima wa `ala ali Ibrahima innaka Hamidum Majid. Allahumma barik `ala Muhammadin wa `ala ali Muhammadin kama barakta `ala Ibrahima wa `ala ali Ibrahima innaka Hamidum Majid.",
    english: 'O Allah, bestow Your grace on Muhammad and on the family of Muhammad, as You bestowed Your grace on Ibrahim and on the family of Ibrahim. You are praiseworthy, Most Glorious. O Allah, bless Muhammad and the family of Muhammad as You blessed Ibrahim and the family of Ibrahim. You are praiseworthy, Most Glorious.',
    reference: 'Bukhari 3370, Muslim 406',
    tags: ['darood', 'salawat', 'prayer'],
  },
  {
    id: 'tashahhud',
    group: 'prayer',
    title: 'Tashahhud (Sitting in Prayer)',
    arabic: 'التَّحِيَّاتُ لِلَّهِ وَالصَّلَوَاتُ وَالطَّيِّبَاتُ، السَّلَامُ عَلَيْكَ أَيُّهَا النَّبِيُّ وَرَحْمَةُ اللَّهِ وَبَرَكَاتُهُ، السَّلَامُ عَلَيْنَا وَعَلَى عِبَادِ اللَّهِ الصَّالِحِينَ، أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا اللَّهُ وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ',
    transliteration: "At-tahiyyatu lillahi was-salawatu wat-tayyibatu, as-salamu `alayka ayyuhan-nabiyyu wa rahmatullahi wa barakatuh, as-salamu `alayna wa `ala `ibadillahis-salihin, ashhadu an la ilaha illallahu wa ashhadu anna Muhammadan `abduhu wa rasuluh.",
    english: 'All greetings of humility are for Allah, and all prayers and goodness. Peace be upon you O Prophet, and the mercy of Allah and His blessings. Peace be upon us and upon the righteous servants of Allah. I bear witness that there is no god but Allah, and I bear witness that Muhammad is His servant and messenger.',
    reference: 'Bukhari 831, Muslim 402',
    tags: ['tashahhud', 'salah', 'prayer'],
  },
  {
    id: 'dua-qunoot',
    group: 'prayer',
    title: 'Dua e Qunoot (Witr Prayer)',
    arabic: 'اللَّهُمَّ اهْدِنَا فِيمَنْ هَدَيْتَ وَعَافِنَا فِيمَنْ عَافَيْتَ وَتَوَلَّنَا فِيمَنْ تَوَلَّيْتَ وَبَارِكْ لَنَا فِيمَا أَعْطَيْتَ وَقِنَا شَرَّ مَا قَضَيْتَ فَإِنَّكَ تَقْضِي وَلَا يُقْضَى عَلَيْكَ وَإِنَّهُ لَا يَذِلُّ مَنْ وَالَيْتَ تَبَارَكْتَ رَبَّنَا وَتَعَالَيْتَ',
    transliteration: "Allahummahdina fiman hadayta wa `afina fiman `afayta wa tawallana fiman tawallayta wa barik lana fima a`tayta wa qina sharra ma qadhayta fa-innaka taqdhi wa la yuqdha `alayka wa innahu la yadhillu man walayta tabarakta Rabbana wa ta`alayt.",
    english: 'O Allah, guide us among those You have guided, grant us wellbeing among those You have granted wellbeing, take us into Your care among those You have taken care of, bless us in what You have given us, and protect us from the evil of what You have decreed. For verily You decree and nothing is decreed upon You, and he is not humiliated whom You have befriended. Blessed are You, our Lord, and Exalted.',
    reference: 'Abu Dawood 1425, Tirmidhi 464',
    tags: ['qunoot', 'witr', 'prayer'],
  },
  {
    id: 'after-prayer-tasbeeh',
    group: 'prayer',
    title: 'After Salah – Tasbeeh',
    arabic: 'سُبْحَانَ اللَّهِ (33) الْحَمْدُ لِلَّهِ (33) اللَّهُ أَكْبَرُ (33)',
    transliteration: 'SubhanAllah (33), Alhamdulillah (33), Allahu Akbar (33).',
    english: 'Glory be to Allah (33x), Praise be to Allah (33x), Allah is the Greatest (33x).',
    reference: 'Muslim 595, Bukhari 843',
    tags: ['tasbeeh', 'after prayer', 'dhikr'],
  },
  {
    id: 'after-prayer-remembrance',
    group: 'prayer',
    title: 'Remembrance After Prayer',
    arabic: 'لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ',
    transliteration: "La ilaha illallahu wahdahu la sharika lahu, lahul mulku wa lahul hamdu wa huwa `ala kulli shay-in qadir.",
    english: 'None has the right to be worshipped but Allah alone, Who has no partner. His is the dominion and His is the praise, and He is able to do all things.',
    reference: 'Muslim 593',
    tags: ['after prayer', 'dhikr', 'tahlil'],
  },
  {
    id: 'start-of-prayer',
    group: 'prayer',
    title: 'After Takbeer – Start of Prayer (Thana)',
    arabic: 'سُبْحَانَكَ اللَّهُمَّ وَبِحَمْدِكَ وَتَبَارَكَ اسْمُكَ وَتَعَالَى جَدُّكَ وَلَا إِلَهَ غَيْرُكَ',
    transliteration: "Subhanakallahumma wa bihamdika wa tabarakasmuka wa ta`ala jadduka wa la ilaha ghayruk.",
    english: 'Glory be to You, O Allah, and praise. Blessed is Your name and Exalted is Your Majesty. There is no god but You.',
    reference: 'Tirmidhi 243, Abu Dawood 775',
    tags: ['thana', 'start of prayer', 'takbeer'],
  },
  {
    id: 'during-ruku',
    group: 'prayer',
    title: 'During Ruku (Bowing in Prayer)',
    arabic: 'سُبْحَانَ رَبِّيَ الْعَظِيمِ',
    transliteration: "Subhana Rabbiyal `Azim.",
    english: 'Glory be to my Lord, the Almighty.',
    reference: 'Muslim 772, Abu Dawood 869',
    tags: ['ruku', 'salah', 'prayer'],
  },
  {
    id: 'while-prostrating',
    group: 'prayer',
    title: 'While Prostrating (Sujood)',
    arabic: 'سُبْحَانَ رَبِّيَ الْأَعْلَى',
    transliteration: "Subhana Rabbiyal A`la.",
    english: 'Glory be to my Lord, the Most High.',
    reference: 'Muslim 772, Abu Dawood 871',
    tags: ['sujood', 'prostration', 'prayer'],
  },
  {
    id: 'between-sujood',
    group: 'prayer',
    title: 'When Sitting Between Two Sujood',
    arabic: 'رَبِّ اغْفِرْ لِي رَبِّ اغْفِرْ لِي',
    transliteration: "Rabbighfir li, Rabbighfir li.",
    english: 'O Lord, forgive me. O Lord, forgive me.',
    reference: 'Ibn Majah 897, Abu Dawood 874',
    tags: ['sujood', 'between prostrations', 'prayer'],
  },
  {
    id: 'offer-salah',
    group: 'prayer',
    title: 'Pledge to Offer Salah Regularly',
    arabic: 'رَبِّ اجْعَلْنِي مُقِيمَ الصَّلَاةِ وَمِن ذُرِّيَّتِي رَبَّنَا وَتَقَبَّلْ دُعَاءِ',
    transliteration: "Rabbij `alni muqimas-salati wa min dhurriyyati, Rabbana wa taqabbal du`a.",
    english: 'My Lord, make me one who establishes prayer and also my descendants. Our Lord, accept my supplication.',
    reference: 'Quran 14:40 – Dua of Ibrahim (AS)',
    tags: ['salah', 'prayer', 'ibadah'],
  },

  // ── HOME & TRAVEL ─────────────────────────────────────────────────────────
  {
    id: 'leaving-home',
    group: 'home',
    title: 'When Leaving Home',
    arabic: 'بِسْمِ اللَّهِ تَوَكَّلْتُ عَلَى اللَّهِ وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ',
    transliteration: "Bismillahi tawakkaltu `alallahi wa la hawla wa la quwwata illa billah.",
    english: 'In the name of Allah, I trust in Allah; there is no power or might except with Allah.',
    reference: 'Abu Dawood 5095, Tirmidhi 3426',
    tags: ['home', 'leaving', 'travel'],
  },
  {
    id: 'entering-home',
    group: 'home',
    title: 'Upon Entering Home',
    arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ خَيْرَ الْمَوْلِجِ وَخَيْرَ الْمَخْرَجِ، بِسْمِ اللَّهِ وَلَجْنَا وَبِسْمِ اللَّهِ خَرَجْنَا وَعَلَى اللَّهِ رَبِّنَا تَوَكَّلْنَا',
    transliteration: "Allahumma inni as-aluka khayral mawliji wa khayral makhraji, bismillahi walajna wa bismillahi kharajna wa `alallahi Rabbina tawakkalna.",
    english: 'O Allah, I ask You for a good entry and a good exit. With the name of Allah we enter, and with the name of Allah we leave, and upon Allah our Lord we place our trust.',
    reference: 'Abu Dawood 5096',
    tags: ['home', 'entering', 'entering home'],
  },
  {
    id: 'entering-mosque',
    group: 'home',
    title: 'Upon Entering Mosque',
    arabic: 'اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ',
    transliteration: "Allahumma iftah li abwaba rahmatik.",
    english: 'O Allah, open the doors of Your mercy for me.',
    reference: 'Muslim 713, Ibn Majah 771',
    tags: ['mosque', 'masjid', 'entering'],
  },
  {
    id: 'leaving-mosque',
    group: 'home',
    title: 'Upon Leaving Mosque',
    arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ',
    transliteration: "Allahumma inni as-aluka min fadlik.",
    english: 'O Allah, I ask You for Your bounty.',
    reference: 'Muslim 713, Ibn Majah 772',
    tags: ['mosque', 'masjid', 'leaving'],
  },
  {
    id: 'going-mosque',
    group: 'home',
    title: 'When Going to Mosque',
    arabic: 'اللَّهُمَّ اجْعَلْ فِي قَلْبِي نُورًا وَفِي لِسَانِي نُورًا وَفِي سَمْعِي نُورًا وَفِي بَصَرِي نُورًا وَمِنْ فَوْقِي نُورًا وَمِنْ تَحْتِي نُورًا وَعَنْ يَمِينِي نُورًا وَعَنْ شِمَالِي نُورًا وَمِنْ أَمَامِي نُورًا وَمِنْ خَلْفِي نُورًا وَاجْعَلْ لِي نُورًا',
    transliteration: "Allahumma-j`al fi qalbi nuran wa fi lisani nuran wa fi sam`i nuran wa fi basari nuran wa min fawqi nuran wa min tahti nuran wa `an yamini nuran wa `an shimali nuran wa min amami nuran wa min khalfi nuran waj`al li nura.",
    english: 'O Allah, place light in my heart, light in my tongue, light in my hearing, light in my sight, light above me, light below me, light to my right, light to my left, light before me, light behind me, and grant me light.',
    reference: 'Muslim 763',
    tags: ['mosque', 'noor', 'light'],
  },
  {
    id: 'going-toilet',
    group: 'home',
    title: 'Before Entering Toilet',
    arabic: 'بِسْمِ اللَّهِ، اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْخُبُثِ وَالْخَبَائِثِ',
    transliteration: "Bismillah, Allahumma inni a`udhu bika minal khubuthi wal khaba-ith.",
    english: 'In the name of Allah. O Allah, I seek refuge in You from male and female evil spirits.',
    reference: 'Bukhari 142, Muslim 375',
    tags: ['toilet', 'bathroom', 'protection'],
  },
  {
    id: 'leaving-toilet',
    group: 'home',
    title: 'After Leaving Toilet',
    arabic: 'غُفْرَانَكَ',
    transliteration: 'Ghufranaka.',
    english: 'I seek Your forgiveness.',
    reference: 'Abu Dawood 30, Tirmidhi 7, Ibn Majah 300',
    tags: ['toilet', 'bathroom', 'forgiveness'],
  },
  {
    id: 'for-travel',
    group: 'home',
    title: 'For Travel (Safar ki Dua)',
    arabic: 'اللَّهُ أَكْبَرُ اللَّهُ أَكْبَرُ اللَّهُ أَكْبَرُ، سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ وَإِنَّا إِلَى رَبِّنَا لَمُنقَلِبُونَ، اللَّهُمَّ إِنَّا نَسْأَلُكَ فِي سَفَرِنَا هَذَا الْبِرَّ وَالتَّقْوَى وَمِنَ الْعَمَلِ مَا تَرْضَى',
    transliteration: "Allahu Akbar (x3), Subhanal-ladhi sakhkhara lana hadha wa ma kunna lahu muqrinin wa inna ila Rabbina lamunqalibun. Allahumma inna nas-aluka fi safarina hadhal birra wat-taqwa wa minal `amali ma tarda.",
    english: 'Allah is the Greatest (x3). Glory be to the One who has subjected this to us, and we were not capable of doing it, and indeed to our Lord we will surely return. O Allah, we ask You in this journey of ours for righteousness and piety, and deeds that are pleasing to You.',
    reference: 'Muslim 1342',
    tags: ['travel', 'safar', 'journey'],
  },
  {
    id: 'returning-travel',
    group: 'home',
    title: 'While Returning from Travel',
    arabic: 'آيِبُونَ تَائِبُونَ عَابِدُونَ لِرَبِّنَا حَامِدُونَ',
    transliteration: "Ayibuna ta-ibuna `abiduna liRabbina hamidun.",
    english: 'We are returning, repenting, worshipping and praising our Lord.',
    reference: 'Muslim 1345',
    tags: ['returning', 'travel', 'safar'],
  },
  {
    id: 'entering-market',
    group: 'home',
    title: 'When Entering Market',
    arabic: 'لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ يُحْيِي وَيُمِيتُ وَهُوَ حَيٌّ لَا يَمُوتُ بِيَدِهِ الْخَيْرُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ',
    transliteration: "La ilaha illallahu wahdahu la sharika lahu, lahul mulku wa lahul hamdu yuhyi wa yumitu wa huwa hayyun la yamutu biyadihil khayru wa huwa `ala kulli shay-in qadir.",
    english: 'There is none worthy of worship except Allah, Alone, without partner. To Him belongs dominion and praise. He gives life and causes death, while He is living and does not die. In His hand is all good and He has power over all things.',
    reference: 'Tirmidhi 3428, Ibn Majah 2235',
    tags: ['market', 'bazaar', 'business'],
  },
  {
    id: 'wearing-clothes',
    group: 'home',
    title: 'When Wearing a Garment',
    arabic: 'الْحَمْدُ لِلَّهِ الَّذِي كَسَانِي هَذَا وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّي وَلَا قُوَّةٍ',
    transliteration: "Alhamdu lillahil-ladhi kasani hadha wa razaqanihi min ghayri hawlin minni wa la quwwah.",
    english: 'All praise is for Allah who has clothed me with this and provided it for me with no power or might from myself.',
    reference: 'Abu Dawood 4023, Tirmidhi 3458',
    tags: ['clothes', 'garment', 'gratitude'],
  },
  {
    id: 'wearing-new-clothes',
    group: 'home',
    title: 'When Wearing New Clothes',
    arabic: 'اللَّهُمَّ لَكَ الْحَمْدُ أَنْتَ كَسَوْتَنِيهِ أَسْأَلُكَ خَيْرَهُ وَخَيْرَ مَا صُنِعَ لَهُ وَأَعُوذُ بِكَ مِنْ شَرِّهِ وَشَرِّ مَا صُنِعَ لَهُ',
    transliteration: "Allahumma lakal hamdu anta kasawtanihi as-aluka khayrahuw wa khayra ma suni`a lahu wa a`udhu bika min sharrihii wa sharri ma suni`a lah.",
    english: 'O Allah, praise be to You. You have clothed me with it. I ask You for the good of it and the good for which it was made, and I seek refuge in You from the evil of it and the evil for which it was made.',
    reference: 'Abu Dawood 4020, Tirmidhi 1767',
    tags: ['new clothes', 'garment'],
  },

  // ── FOOD & DRINK ──────────────────────────────────────────────────────────
  {
    id: 'before-meal',
    group: 'food',
    title: 'When Beginning a Meal (Bismillah)',
    arabic: 'بِسْمِ اللَّهِ',
    transliteration: 'Bismillah.',
    english: 'In the name of Allah.',
    reference: 'Abu Dawood 3767, Tirmidhi 1858',
    tags: ['food', 'bismillah', 'eating'],
  },
  {
    id: 'after-meal',
    group: 'food',
    title: 'After Finishing a Meal',
    arabic: 'الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنَا وَسَقَانَا وَجَعَلَنَا مُسْلِمِينَ',
    transliteration: "Alhamdu lillahil-ladhi at`amana wa saqana wa ja`alana muslimin.",
    english: 'All praise is for Allah who fed us and gave us drink, and made us Muslims.',
    reference: 'Abu Dawood 3850, Tirmidhi 3457',
    tags: ['food', 'after eating', 'gratitude'],
  },
  {
    id: 'dining-someones-house',
    group: 'food',
    title: 'When Dining at Someone\'s House',
    arabic: 'اللَّهُمَّ بَارِكْ لَهُمْ فِيمَا رَزَقْتَهُمْ وَاغْفِرْ لَهُمْ وَارْحَمْهُمْ',
    transliteration: "Allahumma barik lahum fima razaqtahum waghfir lahum warhamhum.",
    english: 'O Allah, bless them in what You have provided for them, and forgive them and have mercy on them.',
    reference: 'Muslim 2042',
    tags: ['food', 'host', 'guest'],
  },
  {
    id: 'someone-offers-meal',
    group: 'food',
    title: 'For Someone who Offers You a Meal',
    arabic: 'أَفْطَرَ عِنْدَكُمُ الصَّائِمُونَ وَأَكَلَ طَعَامَكُمُ الْأَبْرَارُ وَصَلَّتْ عَلَيْكُمُ الْمَلَائِكَةُ',
    transliteration: "Aftara `indakumus sa-imuna wa akala ta`amakumul abraru wa sallat `alaykumul mala-ikah.",
    english: 'May the fasting people break their fast with you, may the pious eat your food, and may the angels pray for you.',
    reference: 'Abu Dawood 3854, Ibn Majah 1747',
    tags: ['food', 'host', 'blessing'],
  },
  {
    id: 'given-drink',
    group: 'food',
    title: 'When Given a Drink',
    arabic: 'اللَّهُمَّ أَطْعِمْ مَنْ أَطْعَمَنِي وَاسْقِ مَنْ سَقَانِي',
    transliteration: "Allahumma at`im man at`amani wasqi man saqani.",
    english: 'O Allah, feed the one who fed me and give drink to the one who gave me drink.',
    reference: 'Muslim 2055',
    tags: ['drink', 'food', 'gratitude'],
  },
  {
    id: 'drinking-milk',
    group: 'food',
    title: 'Upon Drinking Milk',
    arabic: 'اللَّهُمَّ بَارِكْ لَنَا فِيهِ وَزِدْنَا مِنْهُ',
    transliteration: "Allahumma barik lana fihi wa zidna minh.",
    english: 'O Allah, bless it for us and give us more of it.',
    reference: 'Tirmidhi 3455, Ibn Majah 3322',
    tags: ['milk', 'drink', 'blessing'],
  },
  {
    id: 'sacrificing-animal',
    group: 'food',
    title: 'When Sacrificing an Animal (Qurbani)',
    arabic: 'بِسْمِ اللَّهِ وَاللَّهُ أَكْبَرُ، اللَّهُمَّ مِنْكَ وَلَكَ',
    transliteration: "Bismillahi wallahu akbar, Allahumma minka wa lak.",
    english: 'In the name of Allah, and Allah is the Greatest. O Allah, this is from You and for You.',
    reference: 'Ahmad 14317, Abu Dawood 2795',
    tags: ['qurbani', 'sacrifice', 'slaughter'],
  },

  // ── SOCIAL & GATHERINGS ───────────────────────────────────────────────────
  {
    id: 'end-of-gathering',
    group: 'social',
    title: 'At the End of a Gathering (Kaffaratul Majlis)',
    arabic: 'سُبْحَانَكَ اللَّهُمَّ وَبِحَمْدِكَ أَشْهَدُ أَنْ لَا إِلَهَ إِلَّا أَنْتَ أَسْتَغْفِرُكَ وَأَتُوبُ إِلَيْكَ',
    transliteration: "Subhanakallahumma wa bihamdika ashhadu an la ilaha illa anta astaghfiruka wa atubu ilayk.",
    english: 'Glory and praise be to You, O Allah. I testify that there is no god but You. I seek Your forgiveness and turn to You in repentance.',
    reference: 'Abu Dawood 4859, Tirmidhi 3433',
    tags: ['gathering', 'majlis', 'kaffara'],
  },
  {
    id: 'greeting-people',
    group: 'social',
    title: 'For Greeting People (Assalam)',
    arabic: 'السَّلَامُ عَلَيْكُمْ وَرَحْمَةُ اللَّهِ وَبَرَكَاتُهُ',
    transliteration: "As-salamu `alaykum wa rahmatullahi wa barakatuh.",
    english: 'Peace be upon you, and the mercy of Allah and His blessings.',
    reference: 'Bukhari 6230',
    tags: ['greeting', 'salam', 'social'],
  },
  {
    id: 'responding-salam',
    group: 'social',
    title: 'When Responding to Salam',
    arabic: 'وَعَلَيْكُمُ السَّلَامُ وَرَحْمَةُ اللَّهِ وَبَرَكَاتُهُ',
    transliteration: "Wa `alaykumus-salam wa rahmatullahi wa barakatuh.",
    english: 'And upon you be peace, and the mercy of Allah and His blessings.',
    reference: 'Bukhari 6230',
    tags: ['greeting', 'salam', 'reply'],
  },
  {
    id: 'when-sneezing',
    group: 'social',
    title: 'Upon Sneezing',
    arabic: 'الْحَمْدُ لِلَّهِ',
    transliteration: 'Alhamdulillah.',
    english: 'Praise be to Allah.',
    reference: 'Bukhari 6224',
    tags: ['sneezing', 'social'],
  },
  {
    id: 'sneezers-reply',
    group: 'social',
    title: 'Sneeze Reply (Yarhamukallah)',
    arabic: 'يَرْحَمُكَ اللَّهُ – يَهْدِيكُمُ اللَّهُ وَيُصْلِحُ بَالَكُمْ',
    transliteration: "Yarhamukallah – Yahdikumullahu wa yuslihu balakum.",
    english: 'May Allah have mercy on you – May Allah guide you and set your affairs right.',
    reference: 'Bukhari 6224',
    tags: ['sneezing', 'reply', 'social'],
  },
  {
    id: 'someone-insults',
    group: 'social',
    title: 'When Someone Insults You',
    arabic: 'اللَّهُمَّ اغْفِرْ لِي وَلَهُ',
    transliteration: "Allahummaghfir li wa lah.",
    english: 'O Allah, forgive me and forgive him.',
    reference: 'Authenticated supplication',
    tags: ['insult', 'social', 'forgiveness'],
  },
  {
    id: 'someone-praises',
    group: 'social',
    title: 'When Someone Praises You',
    arabic: 'اللَّهُمَّ اجْعَلْنِي خَيْرًا مِمَّا يَظُنُّونَ وَاغْفِرْ لِي مَا لَا يَعْلَمُونَ',
    transliteration: "Allahummaj `alni khayran mimma yazunnun waghfir li ma la ya`lamun.",
    english: 'O Allah, make me better than what they think of me, and forgive me for what they do not know of me.',
    reference: 'Bukhari in Al-Adab Al-Mufrad 761',
    tags: ['praise', 'social'],
  },
  {
    id: 'offering-condolence',
    group: 'social',
    title: 'When Offering Condolence',
    arabic: 'إِنَّ لِلَّهِ مَا أَخَذَ وَلَهُ مَا أَعْطَى وَكُلُّ شَيْءٍ عِنْدَهُ بِأَجَلٍ مُسَمًّى فَاصْبِرْ وَاحْتَسِبْ',
    transliteration: "Inna lillahi ma akhadha wa lahu ma a`ta wa kullu shay-in `indahu bi-ajalin musamman fasbir wahtasib.",
    english: 'Verily to Allah belongs what He took, and to Him belongs what He gave, and everything with Him has an appointed time. So be patient and seek the reward.',
    reference: 'Bukhari 1284',
    tags: ['condolence', 'death', 'patience'],
  },
  {
    id: 'visiting-sick',
    group: 'social',
    title: 'When Visiting the Sick',
    arabic: 'لَا بَأْسَ طَهُورٌ إِنْ شَاءَ اللَّهُ',
    transliteration: "La ba-sa tahurun isha Allah.",
    english: 'Do not worry, it is a purification, if Allah wills.',
    reference: 'Bukhari 3616',
    tags: ['sick', 'illness', 'visiting'],
  },
  {
    id: 'thanking-someone',
    group: 'social',
    title: 'For Thanking Someone',
    arabic: 'جَزَاكَ اللَّهُ خَيْرًا',
    transliteration: "Jazakallahu khayran.",
    english: 'May Allah reward you with goodness.',
    reference: 'Tirmidhi 2035',
    tags: ['thanks', 'gratitude', 'social'],
  },
  {
    id: 'someone-lends-money',
    group: 'social',
    title: 'For Someone who Lends You Money',
    arabic: 'بَارَكَ اللَّهُ لَكَ فِي أَهْلِكَ وَمَالِكَ',
    transliteration: "Barakallahu laka fi ahlika wa malik.",
    english: 'May Allah bless you in your family and in your wealth.',
    reference: 'Ahmad, authenticated',
    tags: ['money', 'loan', 'blessing'],
  },

  // ── PROTECTION & SAFETY ───────────────────────────────────────────────────
  {
    id: 'for-protection-allah',
    group: 'protection',
    title: 'For Protection and Help from Allah',
    arabic: 'حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ',
    transliteration: "Hasbunallahu wa ni`mal wakil.",
    english: 'Allah is sufficient for us, and He is the best Disposer of affairs.',
    reference: 'Quran 3:173 – Said by Ibrahim (AS) and the Companions',
    tags: ['protection', 'trust', 'tawakkul'],
  },
  {
    id: 'for-protection-satan',
    group: 'protection',
    title: 'For Protection from Satan/Shaytan',
    arabic: 'أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ',
    transliteration: "A`udhu billahi minash-shaytanir-rajim.",
    english: 'I seek refuge in Allah from the accursed Shaytan.',
    reference: 'Quran 16:98',
    tags: ['shaitan', 'protection', 'ta`awwudh'],
  },
  {
    id: 'for-protection-shirk',
    group: 'protection',
    title: 'For Fear of Committing Shirk',
    arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ أَنْ أُشْرِكَ بِكَ وَأَنَا أَعْلَمُ وَأَسْتَغْفِرُكَ لِمَا لَا أَعْلَمُ',
    transliteration: "Allahumma inni a`udhu bika an ushrika bika wa ana a`lamu wa astaghfiruka lima la a`lam.",
    english: 'O Allah, I seek refuge in You from knowingly associating partners with You, and I seek Your forgiveness for what I do unknowingly.',
    reference: 'Ahmad 19606 – Authenticated by Al-Albani',
    tags: ['shirk', 'protection', 'monotheism'],
  },
  {
    id: 'for-protection-oppressors',
    group: 'protection',
    title: 'For Protection from Oppressors',
    arabic: 'اللَّهُمَّ احْفَظْنِي مِنْ بَيْنِ يَدَيَّ وَمِنْ خَلْفِي وَعَنْ يَمِينِي وَعَنْ شِمَالِي وَمِنْ فَوْقِي وَأَعُوذُ بِعَظَمَتِكَ أَنْ أُغْتَالَ مِنْ تَحْتِي',
    transliteration: "Allahummahfazni min bayni yadayya wa min khalfi wa `an yamini wa `an shimali wa min fawqi wa a`udhu bi`azamatika an ughtala min tahti.",
    english: 'O Allah, guard me from before me, from behind me, from my right and left, and from above me. I seek refuge in Your greatness lest I be harmed from below me.',
    reference: 'Abu Dawood 5074, Authenticated',
    tags: ['protection', 'oppressor', 'safety'],
  },
  {
    id: 'for-childs-protection',
    group: 'protection',
    title: 'For Your Child\'s Protection',
    arabic: 'أُعِيذُكَ بِكَلِمَاتِ اللَّهِ التَّامَّةِ مِنْ كُلِّ شَيْطَانٍ وَهَامَّةٍ وَمِنْ كُلِّ عَيْنٍ لَامَّةٍ',
    transliteration: "U`idhuka bikalimatillahit-tammati min kulli shaytanin wa hammatin wa min kulli `aynin lammah.",
    english: 'I seek refuge for you in the perfect words of Allah from every devil, every poisonous creature, and every evil eye.',
    reference: 'Bukhari 3371 – Prophet (SAW) made this for Hassan and Hussain (RA)',
    tags: ['child', 'protection', 'evil eye'],
  },
  {
    id: 'for-protection-ignorance',
    group: 'protection',
    title: 'For Protection from Ignorance',
    arabic: 'رَبِّ أَعُوذُ بِكَ مِنْ هَمَزَاتِ الشَّيَاطِينِ وَأَعُوذُ بِكَ رَبِّ أَنْ يَحْضُرُونِ',
    transliteration: "Rabbi a`udhu bika min hamazatish-shayatini wa a`udhu bika Rabbi an yahdurun.",
    english: 'My Lord, I seek refuge in You from the incitements of the devils, and I seek refuge in You, my Lord, lest they be present with me.',
    reference: 'Quran 23:97-98',
    tags: ['ignorance', 'shaitan', 'protection'],
  },

  // ── FORGIVENESS & REPENTANCE ──────────────────────────────────────────────
  {
    id: 'for-forgiveness',
    group: 'forgiveness',
    title: 'For Forgiveness (General)',
    arabic: 'رَبَّنَا ظَلَمْنَا أَنفُسَنَا وَإِنْ لَّمْ تَغْفِرْ لَنَا وَتَرْحَمْنَا لَنَكُونَنَّ مِنَ الْخَاسِرِينَ',
    transliteration: "Rabbana zalamna anfusana wa in lam taghfir lana wa tarhamna lanakunanna minal khasirin.",
    english: 'Our Lord, we have wronged ourselves, and if You do not forgive us and have mercy upon us, we will surely be among the losers.',
    reference: 'Quran 7:23 – Dua of Adam and Hawwa (AS)',
    tags: ['forgiveness', 'tawbah', 'repentance'],
  },
  {
    id: 'forgiveness-parents',
    group: 'forgiveness',
    title: 'Forgiveness for Your Parents and All Muslims',
    arabic: 'رَبِّ اغْفِرْ لِي وَلِوَالِدَيَّ وَلِمَنْ دَخَلَ بَيْتِيَ مُؤْمِنًا وَلِلْمُؤْمِنِينَ وَالْمُؤْمِنَاتِ',
    transliteration: "Rabbighfir li wa liwalidayya wa liman dakhala baytiya mu-minan wa lilmu-minina wal-mu-minat.",
    english: 'My Lord, forgive me, my parents, whoever enters my house as a believer, and all the believing men and women.',
    reference: 'Quran 71:28 – Dua of Nuh (AS)',
    tags: ['parents', 'forgiveness', 'family'],
  },
  {
    id: 'forgiveness-siblings',
    group: 'forgiveness',
    title: 'Forgiveness for Your Siblings',
    arabic: 'رَبَّنَا اغْفِرْ لَنَا وَلِإِخْوَانِنَا الَّذِينَ سَبَقُونَا بِالْإِيمَانِ',
    transliteration: "Rabbanaghfir lana wa li-ikhwaninal-ladhina sabaquna bil-iman.",
    english: 'Our Lord, forgive us and our brothers who preceded us in faith.',
    reference: 'Quran 59:10',
    tags: ['forgiveness', 'siblings', 'believers'],
  },
  {
    id: 'for-parents',
    group: 'forgiveness',
    title: 'For Parents',
    arabic: 'رَّبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا',
    transliteration: "Rabbir hamhuma kama rabbayani saghira.",
    english: 'My Lord, have mercy on both of them as they raised me when I was small.',
    reference: 'Quran 17:24',
    tags: ['parents', 'mercy', 'family'],
  },
  {
    id: 'for-deceased',
    group: 'forgiveness',
    title: 'For the Deceased (Janazah Dua)',
    arabic: 'اللَّهُمَّ اغْفِرْ لَهُ وَارْحَمْهُ وَعَافِهِ وَاعْفُ عَنْهُ وَأَكْرِمْ نُزُلَهُ وَوَسِّعْ مَدْخَلَهُ وَاغْسِلْهُ بِالْمَاءِ وَالثَّلْجِ وَالْبَرَدِ',
    transliteration: "Allahummaghfir lahu warhamhu wa `afihi wa`fu `anhu wa akrim nuzulahu wa wassi` madkhalahu waghsilhu bil-ma-i wath-thalji wal-barad.",
    english: 'O Allah, forgive him and have mercy on him and give him strength and pardon him. Be generous to him and cause his entrance to be wide and wash him with water, snow and ice.',
    reference: 'Muslim 963',
    tags: ['deceased', 'death', 'janazah', 'forgiveness'],
  },
  {
    id: 'placing-deceased-in-grave',
    group: 'forgiveness',
    title: 'When Placing the Deceased in the Grave',
    arabic: 'بِسْمِ اللَّهِ وَعَلَى سُنَّةِ رَسُولِ اللَّهِ',
    transliteration: "Bismillahi wa `ala sunnati rasulillah.",
    english: 'In the name of Allah and according to the Sunnah of the Messenger of Allah.',
    reference: 'Abu Dawood 3213, Tirmidhi 1046',
    tags: ['grave', 'burial', 'janazah'],
  },
  {
    id: 'visiting-graves',
    group: 'forgiveness',
    title: 'When Visiting the Graves',
    arabic: 'السَّلَامُ عَلَيْكُمْ دَارَ قَوْمٍ مُؤْمِنِينَ وَإِنَّا إِنْ شَاءَ اللَّهُ بِكُمْ لَاحِقُونَ',
    transliteration: "As-salamu `alaykum dara qawmin mu-minina wa inna insha Allahu bikum lahiqun.",
    english: 'Peace be upon you, O people of the abode of believers, and we will if Allah wills, join you.',
    reference: 'Muslim 975, Ibn Majah 1547',
    tags: ['graves', 'cemetery', 'ziyarah'],
  },
  {
    id: 'last-moments-life',
    group: 'forgiveness',
    title: 'In the Last Moments of One\'s Life',
    arabic: 'لَا إِلَهَ إِلَّا اللَّهُ',
    transliteration: "La ilaha illallah.",
    english: 'There is no deity except Allah.',
    reference: 'Muslim 916 – The Prophet (SAW) said: "Prompt your dying ones to say La ilaha illallah"',
    tags: ['death', 'last breath', 'shahada'],
  },
  {
    id: 'for-repentance',
    group: 'forgiveness',
    title: 'For Repentance (Tawbah)',
    arabic: 'رَبَّنَا لَا تُؤَاخِذْنَا إِنْ نَسِينَا أَوْ أَخْطَأْنَا',
    transliteration: "Rabbana la tu-akhidhna in nasina aw akhta-na.",
    english: 'Our Lord, do not take us to account if we forget or make a mistake.',
    reference: 'Quran 2:286 (Al-Baqarah)',
    tags: ['repentance', 'forgiveness', 'mistake'],
  },

  // ── SPECIAL & MISCELLANEOUS ───────────────────────────────────────────────
  {
    id: 'for-jannah',
    group: 'special',
    title: 'For Jannah (Paradise)',
    arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ الْجَنَّةَ وَأَعُوذُ بِكَ مِنَ النَّارِ',
    transliteration: "Allahumma inni as-alukal jannata wa a`udhu bika minan-nar.",
    english: 'O Allah, I ask You for Paradise and I seek refuge in You from the Fire.',
    reference: 'Abu Dawood 792',
    tags: ['jannah', 'paradise', 'hellfire'],
  },
  {
    id: 'for-success',
    group: 'special',
    title: 'For Success',
    arabic: 'رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ',
    transliteration: "Rabbana atina fid-dunya hasanatan wa fil-akhirati hasanatan wa qina `adhaban-nar.",
    english: 'Our Lord, give us in this world good and in the Hereafter good and protect us from the punishment of the Fire.',
    reference: 'Quran 2:201, Bukhari 4522',
    tags: ['success', 'dunya', 'akhirah'],
  },
  {
    id: 'for-righteous-company',
    group: 'special',
    title: 'For Righteous Company',
    arabic: 'رَبِّ أَدْخِلْنِي مُدْخَلَ صِدْقٍ وَأَخْرِجْنِي مُخْرَجَ صِدْقٍ وَاجْعَل لِّي مِن لَّدُنكَ سُلْطَانًا نَّصِيرًا',
    transliteration: "Rabbi adkhilni mudkhala sidqin wa akhrini mukhraja sidqin waj`al li min ladunka sultanan nasira.",
    english: 'My Lord, cause me to enter a sound entrance and to exit a sound exit and grant me from Yourself a supporting authority.',
    reference: 'Quran 17:80',
    tags: ['righteous', 'company', 'guidance'],
  },
  {
    id: 'for-rizq',
    group: 'special',
    title: 'For Rizq (Sustenance)',
    arabic: 'اللَّهُمَّ اكْفِنِي بِحَلَالِكَ عَنْ حَرَامِكَ وَأَغْنِنِي بِفَضْلِكَ عَمَّنْ سِوَاكَ',
    transliteration: "Allahummakfini bihalaalika `an haramika wa aghhnini bifadlika `amman siwak.",
    english: 'O Allah, suffice me with Your lawful against Your prohibited, and make me independent of all others besides You.',
    reference: 'Tirmidhi 3563',
    tags: ['rizq', 'sustenance', 'provision'],
  },
  {
    id: 'for-istikhara',
    group: 'special',
    title: 'For Istikhara',
    arabic: 'اللَّهُمَّ إِنِّي أَسْتَخِيرُكَ بِعِلْمِكَ وَأَسْتَقْدِرُكَ بِقُدْرَتِكَ وَأَسْأَلُكَ مِنْ فَضْلِكَ الْعَظِيمِ فَإِنَّكَ تَقْدِرُ وَلَا أَقْدِرُ وَتَعْلَمُ وَلَا أَعْلَمُ وَأَنْتَ عَلَّامُ الْغُيُوبِ',
    transliteration: "Allahumma inni astakhiruka bi`ilmika wa astaqdiruka biqudratika wa as-aluka min fadlikal-`azimi fa-innaka taqdiru wa la aqdiru wa ta`lamu wa la a`lamu wa anta `allamul ghuyub.",
    english: "O Allah, I seek Your guidance by Your knowledge, and I seek ability by Your power, and I ask from Your great bounty. For You are capable and I am not, and You know and I do not, and You are the Knower of the unseen.",
    reference: 'Bukhari 1166',
    tags: ['istikhara', 'guidance', 'decision'],
  },
  {
    id: 'for-patience',
    group: 'special',
    title: 'For Patience (Sabr)',
    arabic: 'رَبَّنَا أَفْرِغْ عَلَيْنَا صَبْرًا وَثَبِّتْ أَقْدَامَنَا وَانْصُرْنَا عَلَى الْقَوْمِ الْكَافِرِينَ',
    transliteration: "Rabbana afrigh `alayna sabran wa thabbit aqdamana wansurna `alal-qawmil-kafirin.",
    english: 'Our Lord, pour upon us patience and plant firmly our feet and give us victory over the disbelieving people.',
    reference: 'Quran 2:250',
    tags: ['patience', 'sabr', 'steadfastness'],
  },
  {
    id: 'for-healthy-life',
    group: 'health',
    title: 'For a Healthy Life',
    arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَافِيَةَ فِي الدُّنْيَا وَالْآخِرَةِ',
    transliteration: "Allahumma inni as-alukal `afiyata fid-dunya wal-akhirah.",
    english: 'O Allah, I ask You for wellbeing in this world and the Hereafter.',
    reference: 'Abu Dawood 5074, Ibn Majah 3871',
    tags: ['health', 'wellbeing', `afiyah`],
  },
  {
    id: 'for-blessing-family',
    group: 'special',
    title: 'For a Blissful Family',
    arabic: 'رَبَّنَا هَبْ لَنَا مِنْ أَزْوَاجِنَا وَذُرِّيَّاتِنَا قُرَّةَ أَعْيُنٍ وَاجْعَلْنَا لِلْمُتَّقِينَ إِمَامًا',
    transliteration: "Rabbana hab lana min azwajina wa dhurriyyatina qurrata a`yunin waj`alna lil-muttaqina imama.",
    english: 'Our Lord, grant us from among our wives and offspring comfort to our eyes and make us an example for the righteous.',
    reference: 'Quran 25:74',
    tags: ['family', 'spouse', 'children'],
  },
  {
    id: 'for-child',
    group: 'special',
    title: 'Asking Allah to Grant You a Child',
    arabic: 'رَبِّ هَبْ لِي مِنَ الصَّالِحِينَ',
    transliteration: "Rabbi hab li minas-salihin.",
    english: 'My Lord, grant me a righteous child.',
    reference: 'Quran 37:100 – Dua of Ibrahim (AS)',
    tags: ['child', 'family', 'offspring'],
  },
  {
    id: 'for-accommodation',
    group: 'special',
    title: 'For Accommodation',
    arabic: 'رَبِّ أَنزِلْنِي مُنزَلًا مُّبَارَكًا وَأَنتَ خَيْرُ الْمُنزِلِينَ',
    transliteration: "Rabbi anzilni munzalan mubarakan wa anta khayrul munzilin.",
    english: 'My Lord, cause me to land at a blessed landing place, and You are the best to accommodate.',
    reference: 'Quran 23:29',
    tags: ['accommodation', 'home', 'travel'],
  },
  {
    id: 'for-controlling-anger',
    group: 'health',
    title: 'For Controlling Your Anger',
    arabic: 'أَعُوذُ بِاللَّهِ مِنَ الشَّيْطَانِ الرَّجِيمِ',
    transliteration: "A`udhu billahi minash-shaytanir-rajim.",
    english: 'I seek refuge in Allah from the accursed Shaytan.',
    reference: 'Bukhari 6048, Muslim 2610 – The Prophet said to seek refuge when angry',
    tags: ['anger', 'control', 'protection'],
  },
  {
    id: 'for-curbing-fear',
    group: 'health',
    title: 'For Curbing Fear',
    arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ وَالْعَجْزِ وَالْكَسَلِ وَالْبُخْلِ وَالْجُبْنِ وَضَلَعِ الدَّيْنِ وَغَلَبَةِ الرِّجَالِ',
    transliteration: "Allahumma inni a`udhu bika minal hammi wal-hazan wal-`ajzi wal-kasali wal-bukhli wal-jubni wa dhala`id-dayni wa ghalabatir-rijal.",
    english: 'O Allah, I seek refuge in You from anxiety, grief, disability, laziness, miserliness, cowardice, the burden of debt, and the overpowering of men.',
    reference: 'Bukhari 2893',
    tags: ['fear', 'anxiety', 'courage'],
  },
  {
    id: 'to-alleviate-pain',
    group: 'health',
    title: 'To Alleviate Pain',
    arabic: 'بِسْمِ اللَّهِ (3 مرات) أَعُوذُ بِعِزَّةِ اللَّهِ وَقُدْرَتِهِ مِنْ شَرِّ مَا أَجِدُ وَأُحَاذِرُ (7 مرات)',
    transliteration: "Bismillah (3x), A`udhu bi`izzatillahi wa qudratih min sharri ma ajidu wa uhaadhir (7x).",
    english: 'In the name of Allah (3x). I seek refuge in the might of Allah and His power from the evil of what I feel and I am wary of (7x). – Place hand on the area of pain.',
    reference: 'Muslim 2202',
    tags: ['pain', 'illness', 'healing', 'ruqyah'],
  },
  {
    id: 'grant-confidence',
    group: 'special',
    title: 'Grant me Confidence and Eloquence',
    arabic: 'رَبِّ اشْرَحْ لِي صَدْرِي وَيَسِّرْ لِي أَمْرِي وَاحْلُلْ عُقْدَةً مِّن لِّسَانِي يَفْقَهُوا قَوْلِي',
    transliteration: "Rabbish-rah li sadri wa yassir li amri wahlul `uqdatan min lisani yafqahu qawli.",
    english: 'My Lord, expand for me my chest, and ease for me my task, and untie the knot from my tongue that they may understand my speech.',
    reference: 'Quran 20:25-28 – Dua of Musa (AS)',
    tags: ['confidence', 'speech', 'eloquence'],
  },
  {
    id: 'for-seeking-allahs-help',
    group: 'special',
    title: 'For Seeking Allah\'s Help',
    arabic: 'إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ',
    transliteration: "Iyyaka na`budu wa iyyaka nasta`in.",
    english: 'You alone we worship, and You alone we ask for help.',
    reference: 'Quran 1:5 (Al-Fatihah)',
    tags: ['help', 'worship', 'ibadah'],
  },
  {
    id: 'if-fall-hard-times',
    group: 'special',
    title: 'If You Fall on Hard Times',
    arabic: 'أَلَا بِذِكْرِ اللَّهِ تَطْمَئِنُّ الْقُلُوبُ',
    transliteration: "Ala bidhikrillahi tatma-innul qulub.",
    english: 'Verily, in the remembrance of Allah do hearts find rest.',
    reference: 'Quran 13:28 (Ar-Ra\'d)',
    tags: ['hard times', 'remembrance', 'dhikr', 'peace'],
  },
  {
    id: 'when-need',
    group: 'special',
    title: 'When You Are in Need',
    arabic: 'اللَّهُمَّ لَا سَهْلَ إِلَّا مَا جَعَلْتَهُ سَهْلًا وَأَنْتَ تَجْعَلُ الْحَزْنَ إِذَا شِئْتَ سَهْلًا',
    transliteration: "Allahumma la sahla illa ma ja`altahu sahlan wa anta taj`alul hazna idha shi-ta sahla.",
    english: 'O Allah, there is no ease except in that which You have made easy, and You make the difficult, if You wish, easy.',
    reference: 'Ibn Hibban 2427 – Authenticated',
    tags: ['need', 'ease', 'difficulty'],
  },
  {
    id: 'when-fail',
    group: 'special',
    title: 'When You Fail or Lose at Something',
    arabic: 'قَدَّرَ اللَّهُ وَمَا شَاءَ فَعَلَ',
    transliteration: "Qaddarallahu wa ma sha-a fa`al.",
    english: 'Allah has decreed and what He wills, He does.',
    reference: 'Muslim 2664',
    tags: ['failure', 'qadar', 'decree'],
  },
  {
    id: 'strengthen-iman',
    group: 'special',
    title: 'Strengthen Your Imaan',
    arabic: 'رَبَّنَا لَا تُزِغْ قُلُوبَنَا بَعْدَ إِذْ هَدَيْتَنَا وَهَبْ لَنَا مِن لَّدُنكَ رَحْمَةً إِنَّكَ أَنتَ الْوَهَّابُ',
    transliteration: "Rabbana la tuzigh qulubana ba`da idh hadaytana wa hab lana min ladunka rahmatan innaka antal Wahhab.",
    english: 'Our Lord, let not our hearts deviate after You have guided us and grant us from Yourself mercy. Indeed, You are the Bestower.',
    reference: 'Quran 3:8 (Al-Imran)',
    tags: ['iman', 'faith', 'guidance'],
  },
  {
    id: 'on-hearing-athan',
    group: 'daily',
    title: 'On Hearing the Athan',
    arabic: 'وَأَنَا أَشْهَدُ أَنْ لَّا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ وَأَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ رَضِيتُ بِاللَّهِ رَبًّا وَبِمُحَمَّدٍ رَسُولًا وَبِالْإِسْلَامِ دِينًا',
    transliteration: "Wa ana ashhadu an la ilaha illallahu wahdahu la sharika lahu wa anna Muhammadan `abduhu wa rasuluh, radhitu billahi rabban wa biMuhammadin rasulan wa bil-islami dinan.",
    english: 'And I bear witness that there is no god but Allah alone, without partner, and that Muhammad is His servant and messenger. I am pleased with Allah as Lord, with Muhammad as Messenger and with Islam as religion.',
    reference: 'Muslim 386',
    tags: ['athan', 'adhan', 'response'],
  },
  {
    id: 'completing-ablution',
    group: 'daily',
    title: 'Upon Completing Ablution (After Wudu)',
    arabic: 'أَشْهَدُ أَنْ لَّا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ، اللَّهُمَّ اجْعَلْنِي مِنَ التَّوَّابِينَ وَاجْعَلْنِي مِنَ الْمُتَطَهِّرِينَ',
    transliteration: "Ashhadu an la ilaha illallahu wahdahu la sharika lahu wa ashhadu anna Muhammadan `abduhu wa rasuluh, Allahummaj`alni minat-tawwabina waj`alni minal-mutatahhirin.",
    english: 'I testify that there is no god but Allah alone, with no partner, and I testify that Muhammad is His servant and messenger. O Allah, make me among those who repent and make me among those who purify themselves.',
    reference: 'Muslim 234, Tirmidhi 55',
    tags: ['wudu', 'ablution', 'purification'],
  },
  {
    id: 'starting-ablution',
    group: 'daily',
    title: 'When Starting Ablution',
    arabic: 'بِسْمِ اللَّهِ',
    transliteration: 'Bismillah.',
    english: 'In the name of Allah.',
    reference: 'Abu Dawood 101, Tirmidhi 25',
    tags: ['wudu', 'ablution', 'purification'],
  },
  {
    id: 'praise-allah',
    group: 'daily',
    title: 'For Praising Allah (Tahmid)',
    arabic: 'الْحَمْدُ لِلَّهِ حَمْدًا كَثِيرًا طَيِّبًا مُبَارَكًا فِيهِ',
    transliteration: "Alhamdu lillahi hamdan kathiran tayyiban mubarakan fih.",
    english: 'All praise is for Allah, abundant, good and blessed praise.',
    reference: 'Bukhari 799, Muslim 600',
    tags: ['praise', 'tahmid', 'gratitude'],
  },
  {
    id: 'being-grateful',
    group: 'special',
    title: 'For Being Grateful to Allah',
    arabic: 'اللَّهُمَّ أَعِنِّي عَلَى ذِكْرِكَ وَشُكْرِكَ وَحُسْنِ عِبَادَتِكَ',
    transliteration: "Allahumma a`inni `ala dhikrika wa shukrika wa husni `ibadatik.",
    english: 'O Allah, help me to remember You, to be grateful to You, and to worship You in the best manner.',
    reference: 'Abu Dawood 1522',
    tags: ['gratitude', 'shukr', 'ibadah'],
  },
  {
    id: 'trust-upon-allah',
    group: 'special',
    title: 'To Trust Upon Allah (Tawakkul)',
    arabic: 'حَسْبِيَ اللَّهُ لَا إِلَهَ إِلَّا هُوَ عَلَيْهِ تَوَكَّلْتُ وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ',
    transliteration: "Hasbiyal-lahu la ilaha illa huwa `alayhi tawakkaltu wa huwa rabbul `arshil `azim.",
    english: 'Sufficient for me is Allah; there is no deity except Him. On Him I have relied, and He is the Lord of the Great Throne.',
    reference: 'Quran 9:129, Abu Dawood 5081',
    tags: ['tawakkul', 'trust', 'reliance'],
  },

  // ── HAJJ & UMRAH ──────────────────────────────────────────────────────────
  {
    id: 'talbiyah',
    group: 'hajj',
    title: 'Talbiyah (Hajj & Umrah)',
    arabic: 'لَبَّيْكَ اللَّهُمَّ لَبَّيْكَ، لَبَّيْكَ لَا شَرِيكَ لَكَ لَبَّيْكَ، إِنَّ الْحَمْدَ وَالنِّعْمَةَ لَكَ وَالْمُلْكَ، لَا شَرِيكَ لَكَ',
    transliteration: "Labbayk Allahumma labbayk, labbayk la sharika laka labbayk, innal hamda wan-ni`mata laka wal-mulk, la sharika lak.",
    english: 'Here I am O Allah, here I am. Here I am, You have no partner, here I am. Indeed all praise, grace and sovereignty belong to You. You have no partner.',
    reference: 'Bukhari 1549, Muslim 1184',
    tags: ['hajj', 'umrah', 'talbiyah', 'ihram'],
  },
  {
    id: 'at-arafat',
    group: 'hajj',
    title: 'At Arafat',
    arabic: 'لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ',
    transliteration: "La ilaha illallahu wahdahu la sharika lahu, lahul mulku wa lahul hamdu wa huwa `ala kulli shay-in qadir.",
    english: 'There is no deity except Allah, Alone, with no partner. To Him belongs the dominion and to Him belongs all praise, and He is over all things competent.',
    reference: 'Tirmidhi 3585 – Best dua on the Day of Arafat',
    tags: ['arafat', 'hajj', 'dua of day'],
  },
  {
    id: 'at-arafat-mashaar',
    group: 'hajj',
    title: 'For Reciting at Al-Mash\'ar Al-Haram',
    arabic: 'رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ',
    transliteration: "Rabbana atina fid-dunya hasanatan wa fil-akhirati hasanatan wa qina `adhaban-nar.",
    english: 'Our Lord, give us good in this world and good in the Hereafter and protect us from the punishment of the Fire.',
    reference: 'Quran 2:201 – Recited at Mash\'ar al-Haram (Muzdalifah)',
    tags: ['muzdalifah', 'mashar', 'hajj'],
  },
  {
    id: 'safa-marwah',
    group: 'hajj',
    title: 'When at Mount Safa and Mount Marwah',
    arabic: 'اللَّهُ أَكْبَرُ، اللَّهُ أَكْبَرُ، اللَّهُ أَكْبَرُ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ',
    transliteration: "Allahu Akbar, Allahu Akbar, Allahu Akbar. La ilaha illallahu wahdahu la sharika lahu.",
    english: 'Allah is the Greatest, Allah is the Greatest, Allah is the Greatest. There is no god but Allah alone, with no partner.',
    reference: 'Muslim 1218',
    tags: ['safa', 'marwah', 'sa\'i', 'hajj'],
  },
  {
    id: 'yemeni-corner',
    group: 'hajj',
    title: 'Upon Reaching the Yemeni Corner During Tawaf',
    arabic: 'رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ',
    transliteration: "Rabbana atina fid-dunya hasanatan wa fil-akhirati hasanatan wa qina `adhaban-nar.",
    english: 'Our Lord, give us good in this world and good in the Hereafter and protect us from the punishment of the Fire.',
    reference: 'Abu Dawood 1892',
    tags: ['tawaf', 'hajj', 'yemeni corner'],
  },
  {
    id: 'black-stone',
    group: 'hajj',
    title: 'Takbeer When Passing the Black Stone',
    arabic: 'بِسْمِ اللَّهِ وَاللَّهُ أَكْبَرُ',
    transliteration: "Bismillahi wallahu akbar.",
    english: 'In the name of Allah, and Allah is the Greatest.',
    reference: 'Ahmad 14903',
    tags: ['hajj', 'tawaf', 'black stone', 'hajar aswad'],
  },
  {
    id: 'throwing-jamaraat',
    group: 'hajj',
    title: 'When Throwing Stones at Jamaraat',
    arabic: 'بِسْمِ اللَّهِ وَاللَّهُ أَكْبَرُ',
    transliteration: "Bismillahi wallahu akbar.",
    english: 'In the name of Allah, and Allah is the Greatest.',
    reference: 'Bukhari 1750',
    tags: ['hajj', 'jamaraat', 'rami'],
  },
  {
    id: 'manzil',
    group: 'protection',
    title: 'Manzil (Collection of Quranic verses for protection)',
    arabic: 'الفاتحة، البقرة 1-5، البقرة 163-164، آية الكرسي، البقرة 285-286، آل عمران 18-19، الأعراف 54-56...',
    transliteration: '(See full Manzil text in any authenticated Islamic book)',
    english: 'Manzil is a collection of Quranic verses and short Surahs recited for protection from evil, magic, and illness. It includes Surah Al-Fatihah, selected verses from Al-Baqarah, Al-Imran, Al-A\'raf, Al-Isra, Al-Mu\'minun, As-Saffat, Al-Ahqaf, Ar-Rahman, Al-Hashr, Al-Jinn, Al-Kafirun, Al-Ikhlas, Al-Falaq, An-Nas.',
    reference: 'Compiled by Maulana Ashraf Ali Thanawi (RA) – Authenticated traditions',
    tags: ['manzil', 'protection', 'ruqyah', 'sihr'],
  },
  {
    id: 'during-hajj',
    group: 'hajj',
    title: 'General Dua During Hajj',
    arabic: 'اللَّهُمَّ حَجٌّ لَا رِيَاءَ فِيهِ وَلَا سُمْعَةَ',
    transliteration: "Allahumma hajjun la riya-a fihi wa la sum`ah.",
    english: 'O Allah, a Hajj with no show-off in it and no seeking of reputation.',
    reference: 'Ibn Majah 2890',
    tags: ['hajj', 'ikhlas', 'sincerity'],
  },
  {
    id: 'upon-sighting-crescent',
    group: 'daily',
    title: 'Upon Sighting of the Crescent Moon',
    arabic: 'اللَّهُ أَكْبَرُ، اللَّهُمَّ أَهِلَّهُ عَلَيْنَا بِالْيُمْنِ وَالْإِيمَانِ وَالسَّلَامَةِ وَالْإِسْلَامِ، رَبِّي وَرَبُّكَ اللَّهُ',
    transliteration: "Allahu Akbar, Allahumma ahillahu alayna bil-yumni wal-iman was-salamati wal-Islam. Rabbi wa Rabbuka Allah.",
    english: 'Allah is the Greatest. O Allah, let it appear with blessing, faith, peace and Islam. My Lord and your Lord is Allah.',
    reference: 'Tirmidhi 3451',
    tags: ['crescent', 'moon', 'new moon'],
  },
  {
    id: 'seeking-guidance',
    group: 'special',
    title: 'Seek Allah\'s Guidance',
    arabic: 'اللَّهُمَّ اهْدِنِي وَسَدِّدْنِي',
    transliteration: "Allahummahdini wa saddidni.",
    english: 'O Allah, guide me and keep me on the straight path.',
    reference: 'Muslim 2725',
    tags: ['guidance', 'hidayah', 'steadfastness'],
  },
  {
    id: 'seek-allahs-satisfaction',
    group: 'special',
    title: 'Seek Allah\'s Satisfaction',
    arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ رِضَاكَ وَالْجَنَّةَ وَأَعُوذُ بِكَ مِنْ سَخَطِكَ وَالنَّارِ',
    transliteration: "Allahumma inni as-aluka ridaka wal-jannata wa a`udhu bika min sakhatika wan-nar.",
    english: 'O Allah, I ask You for Your pleasure and for Paradise, and I seek refuge in You from Your anger and from the Fire.',
    reference: 'Abu Dawood 1519, Nasai 1306',
    tags: ['satisfaction', 'pleasure', 'jannah'],
  },
  {
    id: 'seek-forgiveness-hell',
    group: 'forgiveness',
    title: 'Seek Forgiveness and Protection from Hell',
    arabic: 'اللَّهُمَّ اغْفِرْ لِي وَارْحَمْنِي وَاهْدِنِي وَعَافِنِي وَارْزُقْنِي',
    transliteration: "Allahummaghfir li warhamni wahhdini wa `afini warzuqni.",
    english: 'O Allah, forgive me, have mercy on me, guide me, protect me, and provide for me.',
    reference: 'Muslim 2697',
    tags: ['forgiveness', 'mercy', 'guidance'],
  },
  {
    id: 'seek-protection-culprits',
    group: 'protection',
    title: 'Seek Protection from Culprits',
    arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْفِتَنِ مَا ظَهَرَ مِنْهَا وَمَا بَطَنَ',
    transliteration: "Allahumma inni a`udhu bika minal fitani ma zahara minha wa ma batan.",
    english: 'O Allah, I seek refuge in You from trials, both apparent and hidden.',
    reference: 'Muslim 2867',
    tags: ['fitna', 'trials', 'protection'],
  },
  {
    id: 'settle-debt',
    group: 'special',
    title: 'Settle a Debt (Dua for Debt)',
    arabic: 'اللَّهُمَّ اكْفِنِي بِحَلَالِكَ عَنْ حَرَامِكَ وَأَغْنِنِي بِفَضْلِكَ عَمَّنْ سِوَاكَ',
    transliteration: "Allahummakfini bihalaalika `an haramika wa aghhnini bifadlika `amman siwak.",
    english: 'O Allah, suffice me with what You have made lawful against what is forbidden, and make me independent of all others besides You.',
    reference: 'Tirmidhi 3563',
    tags: ['debt', 'qarz', 'rizq'],
  },
  {
    id: 'pious-muslim',
    group: 'special',
    title: 'To Be a Pious Muslim',
    arabic: 'رَبَّنَا هَبْ لَنَا مِنْ أَزْوَاجِنَا وَذُرِّيَّاتِنَا قُرَّةَ أَعْيُنٍ وَاجْعَلْنَا لِلْمُتَّقِينَ إِمَامًا',
    transliteration: "Rabbana hab lana min azwajina wa dhurriyyatina qurrata a`yunin waj`alna lil-muttaqina imama.",
    english: 'Our Lord, grant us from among our wives and offspring comfort to our eyes and make us a leader for the righteous.',
    reference: 'Quran 25:74',
    tags: ['piety', 'taqwa', 'Muslim'],
  },
  {
    id: 'family-safe-transgressors',
    group: 'protection',
    title: 'To Keep Your Family Safe from Transgressors',
    arabic: 'رَبِّ لَا تَجْعَلْنِي فِي الْقَوْمِ الظَّالِمِينَ',
    transliteration: "Rabbi la taj`alni fil-qawmiz-zalimin.",
    english: 'My Lord, do not place me with the wrongdoing people.',
    reference: 'Quran 23:94',
    tags: ['family', 'protection', 'zalim'],
  },
  {
    id: 'practising-muslims',
    group: 'special',
    title: 'To Make Us Practising Muslims',
    arabic: 'رَبَّنَا تَقَبَّلْ مِنَّا إِنَّكَ أَنتَ السَّمِيعُ الْعَلِيمُ',
    transliteration: "Rabbana taqabbal minna innaka antas-Sami`ul `Alim.",
    english: 'Our Lord, accept from us. Indeed, You are the Hearing, the Knowing.',
    reference: 'Quran 2:127 – Dua of Ibrahim and Ismail (AS)',
    tags: ['acceptance', 'ibadah', 'practising'],
  },
  // ── ADDITIONAL / PREVIOUSLY MISSING DUAS ────────────────────────────────
  {
    id: 'before-starting',
    group: 'daily',
    title: 'Before Starting Anything',
    arabic: 'بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ',
    transliteration: 'Bismillahir-rahmanir-rahim.',
    english: 'In the name of Allah, the Most Gracious, the Most Merciful.',
    reference: 'Quran 1:1 – Recited before any significant action',
    tags: ['bismillah', 'starting', 'daily'],
  },
  {
    id: 'everyday-duas',
    group: 'daily',
    title: 'Everyday Duas (Hasbiyallah)',
    arabic: 'حَسْبِيَ اللَّهُ لَا إِلَهَ إِلَّا هُوَ عَلَيْهِ تَوَكَّلْتُ وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ',
    transliteration: "Hasbiyal-lahu la ilaha illa huwa `alayhi tawakkaltu wa huwa Rabbul-`arshil-`azeem.",
    english: 'Allah is sufficient for me. There is no god but He. I have placed my trust in Him. He is the Lord of the Majestic Throne.',
    reference: 'Quran 9:129, Abu Dawood 5081 – Recite 7 times morning and evening',
    tags: ['daily', 'hasbiyallah', 'tawakkul'],
  },
  {
    id: 'forgiveness-mercy',
    group: 'forgiveness',
    title: 'For Forgiveness and Allah\'s Mercy',
    arabic: 'رَبَّنَا اغْفِرْ لَنَا ذُنُوبَنَا وَكَفِّرْ عَنَّا سَيِّئَاتِنَا وَتَوَفَّنَا مَعَ الْأَبْرَارِ',
    transliteration: "Rabbanaghfir lana dhunubana wa kaffir `anna sayyi-atina wa tawaffana ma`al-abrar.",
    english: 'Our Lord, forgive us our sins and remove from us our misdeeds, and cause us to die with the righteous.',
    reference: 'Quran 3:193 (Al-Imran)',
    tags: ['forgiveness', 'mercy', 'sins'],
  },
  {
    id: 'for-tawakkul',
    group: 'special',
    title: 'For Leaving Everything in the Hands of Allah',
    arabic: 'تَوَكَّلْتُ عَلَى اللَّهِ وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ',
    transliteration: "Tawakkaltu `alallahi wa la hawla wa la quwwata illa billah.",
    english: 'I place my trust in Allah, and there is no power or might except with Allah.',
    reference: 'Tirmidhi 3426',
    tags: ['tawakkul', 'trust', 'reliance'],
  },
  {
    id: 'overcome-weaknesses',
    group: 'special',
    title: 'For Overcoming Your Weaknesses',
    arabic: 'رَبِّ إِنِّي ظَلَمْتُ نَفْسِي فَاغْفِرْ لِي',
    transliteration: "Rabbi inni zalamtu nafsi faghfir li.",
    english: 'My Lord, I have wronged myself, so forgive me.',
    reference: 'Quran 28:16 – Dua of Musa (AS)',
    tags: ['weakness', 'forgiveness', 'self'],
  },
  {
    id: 'protection-wrongdoers',
    group: 'protection',
    title: 'For Protection from the Wrongdoers',
    arabic: 'رَبِّ نَجِّنِي مِنَ الْقَوْمِ الظَّالِمِينَ',
    transliteration: "Rabbi najjini minal-qawmiz-zalimin.",
    english: 'My Lord, save me from the wrongdoing people.',
    reference: 'Quran 28:21 – Dua of Musa (AS)',
    tags: ['protection', 'zalim', 'wrongdoers'],
  },
  {
    id: 'protection-foolishness',
    group: 'protection',
    title: 'Protection from Foolishness',
    arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْجَهْلِ',
    transliteration: "Allahumma inni a`udhu bika minal-jahl.",
    english: 'O Allah, I seek refuge in You from ignorance and foolishness.',
    reference: 'Authenticated supplication (Al-Bukhari in Al-Adab Al-Mufrad)',
    tags: ['foolishness', 'ignorance', 'protection'],
  },
  {
    id: 'see-sneezing',
    group: 'social',
    title: 'When One Sees Someone Sneezing',
    arabic: 'يَرْحَمُكَ اللَّهُ',
    transliteration: 'Yarhamukallah.',
    english: 'May Allah have mercy on you. (Said to the sneezer after they say Alhamdulillah)',
    reference: 'Bukhari 6224',
    tags: ['sneezing', 'observer', 'social'],
  },
  {
    id: 'seeing-trial',
    group: 'social',
    title: 'Upon Seeing Someone Going Through a Trial',
    arabic: 'الْحَمْدُ لِلَّهِ الَّذِي عَافَانِي مِمَّا ابْتَلَاكَ بِهِ وَفَضَّلَنِي عَلَى كَثِيرٍ مِمَّنْ خَلَقَ تَفْضِيلًا',
    transliteration: "Alhamdu lillahil-ladhi `afani mimm-abtalaka bihi wa faddhalani `ala kathirin mimman khalaqa tafdheela.",
    english: 'Praise be to Allah who saved me from what He has tested you with, and greatly favoured me over many of His creation.',
    reference: 'Tirmidhi 3431',
    tags: ['trial', 'blessing', 'gratitude'],
  },
  {
    id: 'opening-fast',
    group: 'food',
    title: 'While Opening Fast',
    arabic: 'اللَّهُمَّ لَكَ صُمْتُ وَبِكَ آمَنْتُ وَعَلَيْكَ تَوَكَّلْتُ وَعَلَى رِزْقِكَ أَفْطَرْتُ',
    transliteration: "Allahumma laka sumtu wa bika amantu wa `alayka tawakkaltu wa `ala rizqika aftartu.",
    english: 'O Allah, for You I fasted, in You I believe, upon You I rely, and with Your provision I break my fast.',
    reference: 'Abu Dawood 2358',
    tags: ['iftar', 'fast', 'breaking fast'],
  },
  {
    id: 'relation-with-wife',
    group: 'special',
    title: 'Having Relation With Wife',
    arabic: 'بِسْمِ اللَّهِ، اللَّهُمَّ جَنِّبْنَا الشَّيْطَانَ وَجَنِّبِ الشَّيْطَانَ مَا رَزَقْتَنَا',
    transliteration: "Bismillah, Allahumma jannibna-sh-shaytana wa jannibish-shaytana ma razaqtana.",
    english: 'In the name of Allah. O Allah, keep the Shaytan away from us, and keep the Shaytan away from what You have blessed us with.',
    reference: 'Bukhari 141, Muslim 1434 – Recited before intimacy with one\'s spouse',
    tags: ['marriage', 'spouse', 'intimacy', 'protection'],
  },
  {
    id: 'nearing-death',
    group: 'special',
    title: 'When You Are Nearing Your Death',
    arabic: 'اللَّهُمَّ اغْفِرْ لِي وَارْحَمْنِي وَأَلْحِقْنِي بِالرَّفِيقِ الْأَعْلَى',
    transliteration: "Allahummaghfir li warhamni wa alhiqni bir-Rafiqil-A`la.",
    english: 'O Allah, forgive me, have mercy on me, and join me with the highest companionship (in the Hereafter).',
    reference: 'Bukhari 4437, Muslim 2444 – Last words of the Prophet (SAW)',
    tags: ['death', 'dying', 'last breath', 'akhira'],
  },
  {
    id: 'thanking-allah',
    group: 'daily',
    title: 'For Thanking Allah (SWT)',
    arabic: 'رَبِّ أَوْزِعْنِي أَنْ أَشْكُرَ نِعْمَتَكَ الَّتِي أَنْعَمْتَ عَلَيَّ وَعَلَى وَالِدَيَّ وَأَنْ أَعْمَلَ صَالِحًا تَرْضَاهُ',
    transliteration: "Rabbi awzi`ni an ashkura ni`matakal-lati an`amta `alayya wa `ala walidayya wa an a`mala salihan tardah.",
    english: 'My Lord, enable me to be grateful for Your favor which You have bestowed upon me and upon my parents, and to do righteousness of which You approve.',
    reference: 'Quran 27:19 – Dua of Sulaiman (AS)',
    tags: ['thanks', 'gratitude', 'shukr', 'parents'],
  },
  {
    id: 'forgiveness-entering-house',
    group: 'forgiveness',
    title: 'For Asking Forgiveness for Yourself and Anyone Who Enters Your House',
    arabic: 'رَبِّ اغْفِرْ لِي وَلِوَالِدَيَّ وَلِمَنْ دَخَلَ بَيْتِيَ مُؤْمِنًا وَلِلْمُؤْمِنِينَ وَالْمُؤْمِنَاتِ',
    transliteration: "Rabbighfir li wa liwalidayya wa liman dakhala baytiya mu-minan wa lilmu-minina wal-mu-minat.",
    english: 'My Lord, forgive me, my parents, and whoever enters my house as a believer, and all the believing men and women.',
    reference: 'Quran 71:28 – Dua of Nuh (AS)',
    tags: ['forgiveness', 'house', 'family', 'believers'],
  },
  {
    id: 'seeking-allahs-help',
    group: 'special',
    title: 'For Justice',
    arabic: 'رَبِّ انصُرْنِي عَلَى الْقَوْمِ الْمُفْسِدِينَ',
    transliteration: "Rabbi-nsurni `alal-qawmil mufsideen.",
    english: 'My Lord, support me against the corrupting people.',
    reference: 'Quran 29:30 – Dua of Lut (AS)',
    tags: ['justice', `support`, 'nasr'],
  },
];
