// Static list of all 114 surahs — name + meta. Sourced from the Uthmani mushaf order.
// Kept local so the Quran page never blocks on a network call to render.
export type Surah = {
  number: number;
  arabic: string;
  englishName: string;
  englishTranslation: string;
  revelation: 'Meccan' | 'Medinan';
  ayahs: number;
};

export const SURAHS: Surah[] = [
  { number: 1, arabic: 'الفاتحة', englishName: 'Al-Fatihah', englishTranslation: 'The Opening', revelation: 'Meccan', ayahs: 7 },
  { number: 2, arabic: 'البقرة', englishName: 'Al-Baqarah', englishTranslation: 'The Cow', revelation: 'Medinan', ayahs: 286 },
  { number: 3, arabic: 'آل عمران', englishName: 'Aal-E-Imran', englishTranslation: 'Family of Imran', revelation: 'Medinan', ayahs: 200 },
  { number: 4, arabic: 'النساء', englishName: 'An-Nisa', englishTranslation: 'The Women', revelation: 'Medinan', ayahs: 176 },
  { number: 5, arabic: 'المائدة', englishName: 'Al-Maidah', englishTranslation: 'The Table Spread', revelation: 'Medinan', ayahs: 120 },
  { number: 6, arabic: 'الأنعام', englishName: 'Al-Anam', englishTranslation: 'The Cattle', revelation: 'Meccan', ayahs: 165 },
  { number: 7, arabic: 'الأعراف', englishName: 'Al-Araf', englishTranslation: 'The Heights', revelation: 'Meccan', ayahs: 206 },
  { number: 8, arabic: 'الأنفال', englishName: 'Al-Anfal', englishTranslation: 'The Spoils of War', revelation: 'Medinan', ayahs: 75 },
  { number: 9, arabic: 'التوبة', englishName: 'At-Tawbah', englishTranslation: 'The Repentance', revelation: 'Medinan', ayahs: 129 },
  { number: 10, arabic: 'يونس', englishName: 'Yunus', englishTranslation: 'Jonah', revelation: 'Meccan', ayahs: 109 },
  { number: 11, arabic: 'هود', englishName: 'Hud', englishTranslation: 'Hud', revelation: 'Meccan', ayahs: 123 },
  { number: 12, arabic: 'يوسف', englishName: 'Yusuf', englishTranslation: 'Joseph', revelation: 'Meccan', ayahs: 111 },
  { number: 13, arabic: 'الرعد', englishName: 'Ar-Rad', englishTranslation: 'The Thunder', revelation: 'Medinan', ayahs: 43 },
  { number: 14, arabic: 'إبراهيم', englishName: 'Ibrahim', englishTranslation: 'Abraham', revelation: 'Meccan', ayahs: 52 },
  { number: 15, arabic: 'الحجر', englishName: 'Al-Hijr', englishTranslation: 'The Rocky Tract', revelation: 'Meccan', ayahs: 99 },
  { number: 16, arabic: 'النحل', englishName: 'An-Nahl', englishTranslation: 'The Bee', revelation: 'Meccan', ayahs: 128 },
  { number: 17, arabic: 'الإسراء', englishName: 'Al-Isra', englishTranslation: 'The Night Journey', revelation: 'Meccan', ayahs: 111 },
  { number: 18, arabic: 'الكهف', englishName: 'Al-Kahf', englishTranslation: 'The Cave', revelation: 'Meccan', ayahs: 110 },
  { number: 19, arabic: 'مريم', englishName: 'Maryam', englishTranslation: 'Mary', revelation: 'Meccan', ayahs: 98 },
  { number: 20, arabic: 'طه', englishName: 'Taha', englishTranslation: 'Ta-Ha', revelation: 'Meccan', ayahs: 135 },
  { number: 21, arabic: 'الأنبياء', englishName: 'Al-Anbiya', englishTranslation: 'The Prophets', revelation: 'Meccan', ayahs: 112 },
  { number: 22, arabic: 'الحج', englishName: 'Al-Hajj', englishTranslation: 'The Pilgrimage', revelation: 'Medinan', ayahs: 78 },
  { number: 23, arabic: 'المؤمنون', englishName: 'Al-Muminun', englishTranslation: 'The Believers', revelation: 'Meccan', ayahs: 118 },
  { number: 24, arabic: 'النور', englishName: 'An-Nur', englishTranslation: 'The Light', revelation: 'Medinan', ayahs: 64 },
  { number: 25, arabic: 'الفرقان', englishName: 'Al-Furqan', englishTranslation: 'The Criterion', revelation: 'Meccan', ayahs: 77 },
  { number: 26, arabic: 'الشعراء', englishName: 'Ash-Shuara', englishTranslation: 'The Poets', revelation: 'Meccan', ayahs: 227 },
  { number: 27, arabic: 'النمل', englishName: 'An-Naml', englishTranslation: 'The Ant', revelation: 'Meccan', ayahs: 93 },
  { number: 28, arabic: 'القصص', englishName: 'Al-Qasas', englishTranslation: 'The Stories', revelation: 'Meccan', ayahs: 88 },
  { number: 29, arabic: 'العنكبوت', englishName: 'Al-Ankabut', englishTranslation: 'The Spider', revelation: 'Meccan', ayahs: 69 },
  { number: 30, arabic: 'الروم', englishName: 'Ar-Rum', englishTranslation: 'The Romans', revelation: 'Meccan', ayahs: 60 },
  { number: 31, arabic: 'لقمان', englishName: 'Luqman', englishTranslation: 'Luqman', revelation: 'Meccan', ayahs: 34 },
  { number: 32, arabic: 'السجدة', englishName: 'As-Sajdah', englishTranslation: 'The Prostration', revelation: 'Meccan', ayahs: 30 },
  { number: 33, arabic: 'الأحزاب', englishName: 'Al-Ahzab', englishTranslation: 'The Combined Forces', revelation: 'Medinan', ayahs: 73 },
  { number: 34, arabic: 'سبأ', englishName: 'Saba', englishTranslation: 'Sheba', revelation: 'Meccan', ayahs: 54 },
  { number: 35, arabic: 'فاطر', englishName: 'Fatir', englishTranslation: 'The Originator', revelation: 'Meccan', ayahs: 45 },
  { number: 36, arabic: 'يس', englishName: 'Ya-Sin', englishTranslation: 'Ya Sin', revelation: 'Meccan', ayahs: 83 },
  { number: 37, arabic: 'الصافات', englishName: 'As-Saffat', englishTranslation: 'Those Who Set The Ranks', revelation: 'Meccan', ayahs: 182 },
  { number: 38, arabic: 'ص', englishName: 'Sad', englishTranslation: 'The Letter Sad', revelation: 'Meccan', ayahs: 88 },
  { number: 39, arabic: 'الزمر', englishName: 'Az-Zumar', englishTranslation: 'The Troops', revelation: 'Meccan', ayahs: 75 },
  { number: 40, arabic: 'غافر', englishName: 'Ghafir', englishTranslation: 'The Forgiver', revelation: 'Meccan', ayahs: 85 },
  { number: 41, arabic: 'فصلت', englishName: 'Fussilat', englishTranslation: 'Explained in Detail', revelation: 'Meccan', ayahs: 54 },
  { number: 42, arabic: 'الشورى', englishName: 'Ash-Shura', englishTranslation: 'The Consultation', revelation: 'Meccan', ayahs: 53 },
  { number: 43, arabic: 'الزخرف', englishName: 'Az-Zukhruf', englishTranslation: 'The Ornaments of Gold', revelation: 'Meccan', ayahs: 89 },
  { number: 44, arabic: 'الدخان', englishName: 'Ad-Dukhan', englishTranslation: 'The Smoke', revelation: 'Meccan', ayahs: 59 },
  { number: 45, arabic: 'الجاثية', englishName: 'Al-Jathiyah', englishTranslation: 'The Crouching', revelation: 'Meccan', ayahs: 37 },
  { number: 46, arabic: 'الأحقاف', englishName: 'Al-Ahqaf', englishTranslation: 'The Wind-Curved Sandhills', revelation: 'Meccan', ayahs: 35 },
  { number: 47, arabic: 'محمد', englishName: 'Muhammad', englishTranslation: 'Muhammad', revelation: 'Medinan', ayahs: 38 },
  { number: 48, arabic: 'الفتح', englishName: 'Al-Fath', englishTranslation: 'The Victory', revelation: 'Medinan', ayahs: 29 },
  { number: 49, arabic: 'الحجرات', englishName: 'Al-Hujurat', englishTranslation: 'The Rooms', revelation: 'Medinan', ayahs: 18 },
  { number: 50, arabic: 'ق', englishName: 'Qaf', englishTranslation: 'The Letter Qaf', revelation: 'Meccan', ayahs: 45 },
  { number: 51, arabic: 'الذاريات', englishName: 'Adh-Dhariyat', englishTranslation: 'The Winnowing Winds', revelation: 'Meccan', ayahs: 60 },
  { number: 52, arabic: 'الطور', englishName: 'At-Tur', englishTranslation: 'The Mount', revelation: 'Meccan', ayahs: 49 },
  { number: 53, arabic: 'النجم', englishName: 'An-Najm', englishTranslation: 'The Star', revelation: 'Meccan', ayahs: 62 },
  { number: 54, arabic: 'القمر', englishName: 'Al-Qamar', englishTranslation: 'The Moon', revelation: 'Meccan', ayahs: 55 },
  { number: 55, arabic: 'الرحمن', englishName: 'Ar-Rahman', englishTranslation: 'The Beneficent', revelation: 'Medinan', ayahs: 78 },
  { number: 56, arabic: 'الواقعة', englishName: 'Al-Waqiah', englishTranslation: 'The Inevitable', revelation: 'Meccan', ayahs: 96 },
  { number: 57, arabic: 'الحديد', englishName: 'Al-Hadid', englishTranslation: 'The Iron', revelation: 'Medinan', ayahs: 29 },
  { number: 58, arabic: 'المجادلة', englishName: 'Al-Mujadilah', englishTranslation: 'The Pleading Woman', revelation: 'Medinan', ayahs: 22 },
  { number: 59, arabic: 'الحشر', englishName: 'Al-Hashr', englishTranslation: 'The Exile', revelation: 'Medinan', ayahs: 24 },
  { number: 60, arabic: 'الممتحنة', englishName: 'Al-Mumtahanah', englishTranslation: 'She That Is To Be Examined', revelation: 'Medinan', ayahs: 13 },
  { number: 61, arabic: 'الصف', englishName: 'As-Saff', englishTranslation: 'The Ranks', revelation: 'Medinan', ayahs: 14 },
  { number: 62, arabic: 'الجمعة', englishName: 'Al-Jumuah', englishTranslation: 'The Congregation', revelation: 'Medinan', ayahs: 11 },
  { number: 63, arabic: 'المنافقون', englishName: 'Al-Munafiqun', englishTranslation: 'The Hypocrites', revelation: 'Medinan', ayahs: 11 },
  { number: 64, arabic: 'التغابن', englishName: 'At-Taghabun', englishTranslation: 'The Mutual Disillusion', revelation: 'Medinan', ayahs: 18 },
  { number: 65, arabic: 'الطلاق', englishName: 'At-Talaq', englishTranslation: 'The Divorce', revelation: 'Medinan', ayahs: 12 },
  { number: 66, arabic: 'التحريم', englishName: 'At-Tahrim', englishTranslation: 'The Prohibition', revelation: 'Medinan', ayahs: 12 },
  { number: 67, arabic: 'الملك', englishName: 'Al-Mulk', englishTranslation: 'The Sovereignty', revelation: 'Meccan', ayahs: 30 },
  { number: 68, arabic: 'القلم', englishName: 'Al-Qalam', englishTranslation: 'The Pen', revelation: 'Meccan', ayahs: 52 },
  { number: 69, arabic: 'الحاقة', englishName: 'Al-Haqqah', englishTranslation: 'The Reality', revelation: 'Meccan', ayahs: 52 },
  { number: 70, arabic: 'المعارج', englishName: 'Al-Maarij', englishTranslation: 'The Ascending Stairways', revelation: 'Meccan', ayahs: 44 },
  { number: 71, arabic: 'نوح', englishName: 'Nuh', englishTranslation: 'Noah', revelation: 'Meccan', ayahs: 28 },
  { number: 72, arabic: 'الجن', englishName: 'Al-Jinn', englishTranslation: 'The Jinn', revelation: 'Meccan', ayahs: 28 },
  { number: 73, arabic: 'المزمل', englishName: 'Al-Muzzammil', englishTranslation: 'The Enshrouded One', revelation: 'Meccan', ayahs: 20 },
  { number: 74, arabic: 'المدثر', englishName: 'Al-Muddaththir', englishTranslation: 'The Cloaked One', revelation: 'Meccan', ayahs: 56 },
  { number: 75, arabic: 'القيامة', englishName: 'Al-Qiyamah', englishTranslation: 'The Resurrection', revelation: 'Meccan', ayahs: 40 },
  { number: 76, arabic: 'الإنسان', englishName: 'Al-Insan', englishTranslation: 'The Man', revelation: 'Medinan', ayahs: 31 },
  { number: 77, arabic: 'المرسلات', englishName: 'Al-Mursalat', englishTranslation: 'The Emissaries', revelation: 'Meccan', ayahs: 50 },
  { number: 78, arabic: 'النبأ', englishName: 'An-Naba', englishTranslation: 'The Tidings', revelation: 'Meccan', ayahs: 40 },
  { number: 79, arabic: 'النازعات', englishName: 'An-Naziat', englishTranslation: 'Those Who Drag Forth', revelation: 'Meccan', ayahs: 46 },
  { number: 80, arabic: 'عبس', englishName: 'Abasa', englishTranslation: 'He Frowned', revelation: 'Meccan', ayahs: 42 },
  { number: 81, arabic: 'التكوير', englishName: 'At-Takwir', englishTranslation: 'The Overthrowing', revelation: 'Meccan', ayahs: 29 },
  { number: 82, arabic: 'الإنفطار', englishName: 'Al-Infitar', englishTranslation: 'The Cleaving', revelation: 'Meccan', ayahs: 19 },
  { number: 83, arabic: 'المطففين', englishName: 'Al-Mutaffifin', englishTranslation: 'The Defrauding', revelation: 'Meccan', ayahs: 36 },
  { number: 84, arabic: 'الإنشقاق', englishName: 'Al-Inshiqaq', englishTranslation: 'The Splitting Open', revelation: 'Meccan', ayahs: 25 },
  { number: 85, arabic: 'البروج', englishName: 'Al-Buruj', englishTranslation: 'The Mansions of the Stars', revelation: 'Meccan', ayahs: 22 },
  { number: 86, arabic: 'الطارق', englishName: 'At-Tariq', englishTranslation: 'The Morning Star', revelation: 'Meccan', ayahs: 17 },
  { number: 87, arabic: 'الأعلى', englishName: 'Al-Ala', englishTranslation: 'The Most High', revelation: 'Meccan', ayahs: 19 },
  { number: 88, arabic: 'الغاشية', englishName: 'Al-Ghashiyah', englishTranslation: 'The Overwhelming', revelation: 'Meccan', ayahs: 26 },
  { number: 89, arabic: 'الفجر', englishName: 'Al-Fajr', englishTranslation: 'The Dawn', revelation: 'Meccan', ayahs: 30 },
  { number: 90, arabic: 'البلد', englishName: 'Al-Balad', englishTranslation: 'The City', revelation: 'Meccan', ayahs: 20 },
  { number: 91, arabic: 'الشمس', englishName: 'Ash-Shams', englishTranslation: 'The Sun', revelation: 'Meccan', ayahs: 15 },
  { number: 92, arabic: 'الليل', englishName: 'Al-Layl', englishTranslation: 'The Night', revelation: 'Meccan', ayahs: 21 },
  { number: 93, arabic: 'الضحى', englishName: 'Ad-Duha', englishTranslation: 'The Morning Hours', revelation: 'Meccan', ayahs: 11 },
  { number: 94, arabic: 'الشرح', englishName: 'Ash-Sharh', englishTranslation: 'The Relief', revelation: 'Meccan', ayahs: 8 },
  { number: 95, arabic: 'التين', englishName: 'At-Tin', englishTranslation: 'The Fig', revelation: 'Meccan', ayahs: 8 },
  { number: 96, arabic: 'العلق', englishName: 'Al-Alaq', englishTranslation: 'The Clot', revelation: 'Meccan', ayahs: 19 },
  { number: 97, arabic: 'القدر', englishName: 'Al-Qadr', englishTranslation: 'The Power', revelation: 'Meccan', ayahs: 5 },
  { number: 98, arabic: 'البينة', englishName: 'Al-Bayyinah', englishTranslation: 'The Clear Proof', revelation: 'Medinan', ayahs: 8 },
  { number: 99, arabic: 'الزلزلة', englishName: 'Az-Zalzalah', englishTranslation: 'The Earthquake', revelation: 'Medinan', ayahs: 8 },
  { number: 100, arabic: 'العاديات', englishName: 'Al-Adiyat', englishTranslation: 'The Courser', revelation: 'Meccan', ayahs: 11 },
  { number: 101, arabic: 'القارعة', englishName: 'Al-Qariah', englishTranslation: 'The Calamity', revelation: 'Meccan', ayahs: 11 },
  { number: 102, arabic: 'التكاثر', englishName: 'At-Takathur', englishTranslation: 'The Rivalry in World Increase', revelation: 'Meccan', ayahs: 8 },
  { number: 103, arabic: 'العصر', englishName: 'Al-Asr', englishTranslation: 'The Declining Day', revelation: 'Meccan', ayahs: 3 },
  { number: 104, arabic: 'الهمزة', englishName: 'Al-Humazah', englishTranslation: 'The Traducer', revelation: 'Meccan', ayahs: 9 },
  { number: 105, arabic: 'الفيل', englishName: 'Al-Fil', englishTranslation: 'The Elephant', revelation: 'Meccan', ayahs: 5 },
  { number: 106, arabic: 'قريش', englishName: 'Quraysh', englishTranslation: 'Quraysh', revelation: 'Meccan', ayahs: 4 },
  { number: 107, arabic: 'الماعون', englishName: 'Al-Maun', englishTranslation: 'The Small Kindnesses', revelation: 'Meccan', ayahs: 7 },
  { number: 108, arabic: 'الكوثر', englishName: 'Al-Kawthar', englishTranslation: 'The Abundance', revelation: 'Meccan', ayahs: 3 },
  { number: 109, arabic: 'الكافرون', englishName: 'Al-Kafirun', englishTranslation: 'The Disbelievers', revelation: 'Meccan', ayahs: 6 },
  { number: 110, arabic: 'النصر', englishName: 'An-Nasr', englishTranslation: 'The Divine Support', revelation: 'Medinan', ayahs: 3 },
  { number: 111, arabic: 'المسد', englishName: 'Al-Masad', englishTranslation: 'The Palm Fibre', revelation: 'Meccan', ayahs: 5 },
  { number: 112, arabic: 'الإخلاص', englishName: 'Al-Ikhlas', englishTranslation: 'The Sincerity', revelation: 'Meccan', ayahs: 4 },
  { number: 113, arabic: 'الفلق', englishName: 'Al-Falaq', englishTranslation: 'The Daybreak', revelation: 'Meccan', ayahs: 5 },
  { number: 114, arabic: 'الناس', englishName: 'An-Nas', englishTranslation: 'The Mankind', revelation: 'Meccan', ayahs: 6 },
];
