// AUTO-GENERATED — localized surah (chapter) names by language.
// Source: quran.com API v4 /chapters?language=<code>, field translated_name.
// Regenerate with scratchpad/gen-surah-names.mjs. Do not hand-edit.
// Languages: en, ur, tr, bn, zh, fr, fa, ru, kk, de, es, nl, it, sv, bs, sq, pl, pt.

export const SURAH_NAMES_BY_LANG: Record<number, Record<string, string>> = {
  1: { en: "The Opener", ur: "کھولنے والی", tr: "Fâtiha", bn: "সূচনা", zh: "开端章", fr: "L'ouverture", fa: "The Opener", ru: "Открывающая Коран", kk: "The Opener", de: "The Opener", es: "La Apertura", nl: "De Opening", it: "L'Aprente", sv: "Öppningen", bs: "Pristup", sq: "The Opener", pl: "The Opener", pt: "The Opener" },
  2: { en: "The Cow", ur: "گائے", tr: "Bakara", bn: "বকনা-বাছুর", zh: "黄牛", fr: "La vache", fa: "The Cow", ru: "Корова", kk: "The Cow", de: "The Cow", es: "La Vaca", nl: "De Koe", it: "La Giovenca", sv: "Kon", bs: "Krava", sq: "The Cow", pl: "The Cow", pt: "The Cow" },
  3: { en: "Family of Imran", ur: "عمران کا خاندان", tr: "Âl-i İmrân", bn: "ইমরানের পরিবার", zh: "仪姆兰的家属", fr: "La famille de 'imran", fa: "Family of Imran", ru: "Семейство Имрана", kk: "Family of Imran", de: "Family of Imran", es: "La Familia de Imran", nl: "De Familie van Imraan", it: "La Famiglia di Imran", sv: "Imrans Ätt", bs: "Imranova porodica", sq: "Family of Imran", pl: "Family of Imran", pt: "Family of Imran" },
  4: { en: "The Women", ur: "عورت", tr: "Nisâ", bn: "নারী", zh: "妇女", fr: "Les femmes", fa: "The Women", ru: "Женщины", kk: "The Women", de: "The Women", es: "Las Mujeres", nl: "De Vrouwen", it: "Le Donne", sv: "Kvinnor", bs: "Žene", sq: "The Women", pl: "The Women", pt: "The Women" },
  5: { en: "The Table Spread", ur: "دسترخوان", tr: "Mâide", bn: "খাদ্য পরিবেশিত টেবিল", zh: "筵席", fr: "La table servie", fa: "The Table Spread", ru: "Трапеза", kk: "The Table Spread", de: "The Table Spread", es: "La Mesa Servida", nl: "De Gedekte Tafel", it: "La Tavola Imbandita", sv: "Den Himmelska Måltiden", bs: "Trpeza", sq: "The Table Spread", pl: "The Table Spread", pt: "The Table Spread" },
  6: { en: "The Cattle", ur: "مویشی", tr: "En'âm", bn: "গৃহপালিত পশু", zh: "牲畜", fr: "Les bestiaux", fa: "The Cattle", ru: "Скот", kk: "The Cattle", de: "The Cattle", es: "Los Rebaños", nl: "Het Vee", it: "Il bestiame", sv: "Boskap", bs: "Stoka", sq: "The Cattle", pl: "The Cattle", pt: "The Cattle" },
  7: { en: "The Heights", ur: "اونچی جگہ", tr: "A'râf", bn: "উচু স্থান", zh: "高处", fr: "Al-A'raf", fa: "The Heights", ru: "Ограды", kk: "The Heights", de: "The Heights", es: "Los Lugares Elevados", nl: "De Verheven Plaatsen", it: "Al-Arтf", sv: "Urskiljning", bs: "Bedemi", sq: "The Heights", pl: "The Heights", pt: "The Heights" },
  8: { en: "The Spoils of War", ur: "مال غنیمت", tr: "Enfâl", bn: "যুদ্ধ-লব্ধ ধনসম্পদ", zh: "战利品", fr: "Le butin", fa: "The Spoils of War", ru: "Трофеи", kk: "The Spoils of War", de: "The Spoils of War", es: "Los Botines de Guerra", nl: "De Oorlogsbuit", it: "Il Bottino", sv: "Krigsbyte", bs: "Plijen", sq: "The Spoils of War", pl: "The Spoils of War", pt: "The Spoils of War" },
  9: { en: "The Repentance", ur: "توبہ", tr: "Tevbe", bn: "অনুশোচনা", zh: "忏悔", fr: "Le repentir", fa: "The Repentance", ru: "Покаяние", kk: "The Repentance", de: "The Repentance", es: "El Arrepentimiento", nl: "Het Berouw", it: "Il Pentimento o la Disapprovazione", sv: "Ånger", bs: "Pokajanje", sq: "The Repentance", pl: "The Repentance", pt: "The Repentance" },
  10: { en: "Jonah", ur: "یونس", tr: "Yûnus", bn: "নবী ইউনুস", zh: "优努斯", fr: "Jonas", fa: "Jonah", ru: "Йунус", kk: "Jonah", de: "Jonah", es: "Jonás", nl: "Jonas", it: "Giona", sv: "Jonah", bs: "Junus", sq: "Jonah", pl: "Jonah", pt: "Jonah" },
  11: { en: "Hud", ur: "حود", tr: "Hûd", bn: "নবী হুদ", zh: "呼德", fr: "Houd", fa: "Hud", ru: "Худ", kk: "Hud", de: "Hud", es: "Hud", nl: "Hoed (de Profeet)", it: "Hћd", sv: "Hud", bs: "Hud", sq: "Hud", pl: "Hud", pt: "Hud" },
  12: { en: "Joseph", ur: "یوسف", tr: "Yûsuf", bn: "নবী ইউসুফ", zh: "优素福", fr: "Joseph", fa: "Joseph", ru: "Йусуф", kk: "Joseph", de: "Joseph", es: "José", nl: "Jozef", it: "Giuseppe", sv: "Josef", bs: "Jusuf", sq: "Joseph", pl: "Joseph", pt: "Joseph" },
  13: { en: "The Thunder", ur: "گرج", tr: "Ra'd", bn: "বজ্রপাত", zh: "雷霆", fr: "Le tonnerre", fa: "The Thunder", ru: "Гром", kk: "The Thunder", de: "The Thunder", es: "El Trueno", nl: "De Donder", it: "Il Tuono", sv: "Åskan", bs: "Grom", sq: "The Thunder", pl: "The Thunder", pt: "The Thunder" },
  14: { en: "Abraham", ur: "ابراہیم", tr: "İbrâhîm", bn: "নবী ইবরাহীম", zh: "易卜拉欣", fr: "Abraham", fa: "Abraham", ru: "Ибрахим", kk: "Abraham", de: "Abraham", es: "Abraham", nl: "Abraham", it: "Abramo", sv: "Abraham", bs: "Ibrahim", sq: "Abraham", pl: "Abraham", pt: "Abraham" },
  15: { en: "The Rocky Tract", ur: "پتھر", tr: "Hicr", bn: "পাথুরে পাহাড়", zh: "石谷", fr: "Al-Hijr", fa: "The Rocky Tract", ru: "Хиджр ", kk: "The Rocky Tract", de: "The Rocky Tract", es: "Al-Hiyr", nl: "De Rotsachtige Streek", it: "Al-Hijr", sv: "Al-Hijr", bs: "Hidžr", sq: "The Rocky Tract", pl: "The Rocky Tract", pt: "The Rocky Tract" },
  16: { en: "The Bee", ur: "شہد کی مکھی", tr: "Nahl", bn: "মৌমাছি", zh: "蜜蜂", fr: "Les abeilles", fa: "The Bee", ru: "Пчелы", kk: "The Bee", de: "The Bee", es: "Las Abejas", nl: "De Bijen", it: "Le Api", sv: "Biet", bs: "Pčele", sq: "The Bee", pl: "The Bee", pt: "The Bee" },
  17: { en: "The Night Journey", ur: "رات کا صفر", tr: "İsrâ", bn: "ইহুদি জাতি", zh: "夜行", fr: "Le voyage nocturne", fa: "The Night Journey", ru: "Ночной перенос", kk: "The Night Journey", de: "The Night Journey", es: "El Viaje Nocturno", nl: "De Nachtelijke Reis", it: "Il Viaggio Notturno", sv: "Den Nattliga Resan", bs: "Noćno putovanje", sq: "The Night Journey", pl: "The Night Journey", pt: "The Night Journey" },
  18: { en: "The Cave", ur: "غار", tr: "Kehf", bn: "গুহা", zh: "山洞", fr: "La caverne", fa: "The Cave", ru: "Пещера", kk: "The Cave", de: "The Cave", es: "La Caverna", nl: "De Grot", it: "La Caverna", sv: "Grottan", bs: "Pećina", sq: "The Cave", pl: "The Cave", pt: "The Cave" },
  19: { en: "Mary", ur: "مریم", tr: "Meryem", bn: "মারইয়াম (ঈসা নবীর মা)", zh: "麦尔彦", fr: "Marie", fa: "Mary", ru: "Марьям", kk: "Mary", de: "Mary", es: "María", nl: "Maria", it: "Maria", sv: "Maria", bs: "Merjema", sq: "Mary", pl: "Mary", pt: "Mary" },
  20: { en: "Ta-Ha", ur: "طٰہٰ", tr: "Tâhâ", bn: "ত়া হা", zh: "塔哈", fr: "Ta-Ha", fa: "Ta-Ha", ru: "Та Ха ", kk: "Ta-Ha", de: "Ta-Ha", es: "Ta-Ha", nl: "Taa Haa (de letters)", it: "Tт-Hт", sv: "Ta-Ha", bs: "Taha", sq: "Ta-Ha", pl: "Ta-Ha", pt: "Ta-Ha" },
  21: { en: "The Prophets", ur: "پیغمبر", tr: "Enbiyâ", bn: "নবীগণ", zh: "众先知", fr: "Les prophètes", fa: "The Prophets", ru: "Пророки", kk: "The Prophets", de: "The Prophets", es: "Los Profetas", nl: "De Profeten", it: "I Profeti", sv: "Profeterna", bs: "Vjerovjesnici", sq: "The Prophets", pl: "The Prophets", pt: "The Prophets" },
  22: { en: "The Pilgrimage", ur: "حج", tr: "Hac", bn: "হ়াজ্জ", zh: "朝觐", fr: "Le pèlerinage", fa: "The Pilgrimage", ru: "Паломничество", kk: "The Pilgrimage", de: "The Pilgrimage", es: "La Peregrinación", nl: "De Bedevaart", it: "Il Pellegrinaggio", sv: "Vallfärden", bs: "Hadždž", sq: "The Pilgrimage", pl: "The Pilgrimage", pt: "The Pilgrimage" },
  23: { en: "The Believers", ur: "مومنین", tr: "Mü'minûn", bn: "বিশ্বাসী", zh: "信士", fr: "Les croyants", fa: "The Believers", ru: "Верующие", kk: "The Believers", de: "The Believers", es: "Los Creyentes", nl: "De Gelovigen", it: "I Credenti", sv: "De Troende", bs: "Vjernici", sq: "The Believers", pl: "The Believers", pt: "The Believers" },
  24: { en: "The Light", ur: "نور", tr: "Nûr", bn: "আলো", zh: "光明", fr: "La lumière", fa: "The Light", ru: "Свет", kk: "The Light", de: "The Light", es: "La Luz", nl: "Het Licht", it: "La Luce", sv: "Ljus", bs: "Svjetlost", sq: "The Light", pl: "The Light", pt: "The Light" },
  25: { en: "The Criterion", ur: "صحیح اور غلط میں فرق کرنے والی کتاب", tr: "Furkân", bn: "মানদণ্ড", zh: "准则", fr: "Le discernement", fa: "The Criterion", ru: "аль-Фуркан", kk: "The Criterion", de: "The Criterion", es: "El Discernimiento", nl: "Het Onderscheidingsmiddel", it: "Il Discrimine", sv: "Måttstocken", bs: "Furkan", sq: "The Criterion", pl: "The Criterion", pt: "The Criterion" },
  26: { en: "The Poets", ur: "شعراٗ", tr: "Şuarâ", bn: "কবি", zh: "众诗人", fr: "Les poètes", fa: "The Poets", ru: "Поэты", kk: "The Poets", de: "The Poets", es: "Los Poetas", nl: "De Dichters", it: "I Poeti", sv: "Poeterna", bs: "Pjesnici", sq: "The Poets", pl: "The Poets", pt: "The Poets" },
  27: { en: "The Ant", ur: "چیونٹی", tr: "Neml", bn: "পিঁপড়া", zh: "蚂蚁", fr: "Les fourmis", fa: "The Ant", ru: "Муравьи", kk: "The Ant", de: "The Ant", es: "Las Hormigas", nl: "De Mieren", it: "Le Formiche", sv: "Myrorna", bs: "Mravi", sq: "The Ant", pl: "The Ant", pt: "The Ant" },
  28: { en: "The Stories", ur: "قصے", tr: "Kasas", bn: "কাহিনি", zh: "故事", fr: "Le récit", fa: "The Stories", ru: "Рассказ", kk: "The Stories", de: "The Stories", es: "Los Relatos", nl: "Het Verhaal", it: "Il Racconto", sv: "Berättelsen", bs: "Kazivanje", sq: "The Stories", pl: "The Stories", pt: "The Stories" },
  29: { en: "The Spider", ur: "مکڑی", tr: "Ankebût", bn: "মাকড়শা", zh: "蜘蛛", fr: "L'araignée", fa: "The Spider", ru: "Паук", kk: "The Spider", de: "The Spider", es: "La Araña", nl: "De Spin", it: "Il Ragno", sv: "Spindeln", bs: "Pauk", sq: "The Spider", pl: "The Spider", pt: "The Spider" },
  30: { en: "The Romans", ur: "روم", tr: "Rûm", bn: "রোমান জাতি", zh: "罗马人", fr: "Les romains", fa: "The Romans", ru: "Римляне", kk: "The Romans", de: "The Romans", es: "Los Romanos", nl: "De Romeinen", it: "I Romani", sv: "Bysantinerna", bs: "Bizantinci", sq: "The Romans", pl: "The Romans", pt: "The Romans" },
  31: { en: "Luqman", ur: "لقمان", tr: "Lokmân", bn: "এক জ্ঞানী ব্যাক্তি", zh: "鲁格曼", fr: "Louqman", fa: "Luqman", ru: "Лукман", kk: "Luqman", de: "Luqman", es: "Luqmán", nl: "Loeqmaan", it: "Luqmрn", sv: "Luqman", bs: "Lukman", sq: "Luqman", pl: "Luqman", pt: "Luqman" },
  32: { en: "The Prostration", ur: "سجدہ", tr: "Secde", bn: "সিজদা", zh: "叩头", fr: "La prosternation", fa: "The Prostration", ru: "Земной поклон", kk: "The Prostration", de: "The Prostration", es: "La Postración", nl: "De Neerknieling", it: "La Prosternazione", sv: "De Faller Ned I Tillbedjan", bs: "Padanje ničice", sq: "The Prostration", pl: "The Prostration", pt: "The Prostration" },
  33: { en: "The Combined Forces", ur: "متحد گروہ", tr: "Ahzâb", bn: "জোট", zh: "同盟军", fr: "Les coalisés", fa: "The Combined Forces", ru: "Союзники", kk: "The Combined Forces", de: "The Combined Forces", es: "Los Coligados", nl: "De Bondgenoten", it: "I Coalizzati", sv: "De Sammansvurna", bs: "Saveznici", sq: "The Combined Forces", pl: "The Combined Forces", pt: "The Combined Forces" },
  34: { en: "Sheba", ur: "سبا", tr: "Sebe'", bn: "রানী সাবা/শেবা", zh: "赛伯邑", fr: "Saba'", fa: "Sheba", ru: "Сава", kk: "Sheba", de: "Sheba", es: "Saba", nl: "De Stad Sheba", it: "Sabт", sv: "Saba", bs: "Saba", sq: "Sheba", pl: "Sheba", pt: "Sheba" },
  35: { en: "Originator", ur: "پیدا کرنے والا", tr: "Fâtır", bn: "আদি স্রষ্টা", zh: "创造者", fr: "Le Créateur", fa: "Originator", ru: "Творец", kk: "Originator", de: "Originator", es: "El Originador", nl: "De Schepper", it: "Colui Che dр origine", sv: "Himlarnas Och Jordens Skapare", bs: "Stvoritelj", sq: "Originator", pl: "Originator", pt: "Originator" },
  36: { en: "Ya Sin", ur: "یٰسٓ", tr: "Yâsîn", bn: "ইয়াসীন", zh: "雅辛", fr: "Ya-Sin", fa: "Ya Sin", ru: "Йа Син", kk: "Ya Sin", de: "Ya Sin", es: "Ya Sin", nl: "Jaa Sien (de letters)", it: "Yт Sюn", sv: "Ya-Sin", bs: "Jasin", sq: "Ya Sin", pl: "Ya Sin", pt: "Ya Sin" },
  37: { en: "Those who set the Ranks", ur: "صف باندھنے والے", tr: "Sâffât", bn: "সারিবদ্ধভাবে দাঁড়ানো", zh: "列班者", fr: "Les rangés", fa: "Those who set the Ranks", ru: "Выстроившиеся в ряды", kk: "Those who set the Ranks", de: "Those who set the Ranks", es: "Los Que se Ponen en Filas", nl: "Die in Rijen staan", it: "I Ranghi", sv: "I Sluten Ordning", bs: "Redovi", sq: "Those who set the Ranks", pl: "Those who set the Ranks", pt: "Those who set the Ranks" },
  38: { en: "The Letter \"Saad\"", ur: "صٓ", tr: "Sâd", bn: "আরবি বর্ণ সাদ", zh: "萨德", fr: "Sad", fa: "The Letter \"Saad\"", ru: "Сод", kk: "The Letter \"Saad\"", de: "The Letter \"Saad\"", es: "Sad", nl: "Saad (de letter)", it: "Sтd", sv: "Sad", bs: "Sad", sq: "The Letter \"Saad\"", pl: "The Letter \"Saad\"", pt: "The Letter \"Saad\"" },
  39: { en: "The Troops", ur: "گروہ", tr: "Zümer", bn: "দলবদ্ধ জনতা", zh: "队伍", fr: "Les groupes", fa: "The Troops", ru: "Толпы", kk: "The Troops", de: "The Troops", es: "Los Grupos", nl: "De Groepen", it: "I Gruppi", sv: "Skarorna", bs: "Skupovi", sq: "The Troops", pl: "The Troops", pt: "The Troops" },
  40: { en: "The Forgiver", ur: "بخشنے والا", tr: "Mü'min", bn: "ক্ষমাকারী", zh: "赦宥者", fr: "Le Pardonneur", fa: "The Forgiver", ru: "Прощающий", kk: "The Forgiver", de: "The Forgiver", es: "El Perdonador", nl: "Hij die Vergeeft", it: "Il Perdonatore", sv: "Han Som Förlåter", bs: "Vjernik", sq: "The Forgiver", pl: "The Forgiver", pt: "The Forgiver" },
  41: { en: "Explained in Detail", ur: "مفصل", tr: "Fussilet", bn: "সুস্পষ্ট বিবরণ", zh: "奉绥来特", fr: "Les versets explicites", fa: "Explained in Detail", ru: "Разъяснены", kk: "Explained in Detail", de: "Explained in Detail", es: "Se Han Expresado Con Claridad", nl: "Gedetailleerde Verzen", it: "Esposti chiaramente", sv: "En Fast Och Klar Förkunnelse", bs: "Objašnjenje", sq: "Explained in Detail", pl: "Explained in Detail", pt: "Explained in Detail" },
  42: { en: "The Consultation", ur: "شورٰی", tr: "Şûrâ", bn: "পরামর্শ", zh: "协商", fr: "La concertation", fa: "The Consultation", ru: "Совет", kk: "The Consultation", de: "The Consultation", es: "La Consulta", nl: "Het Overleg", it: "La Consultazione", sv: "Samråd", bs: "Dogovaranje", sq: "The Consultation", pl: "The Consultation", pt: "The Consultation" },
  43: { en: "The Ornaments of Gold", ur: "سونے کی چمک", tr: "Zuhruf", bn: "সোনাদানা", zh: "金饰", fr: "L'ornement", fa: "The Ornaments of Gold", ru: "Украшения", kk: "The Ornaments of Gold", de: "The Ornaments of Gold", es: "Los Dorados", nl: "De Gouden Juwelen", it: "Gli Ornamenti d'Oro", sv: "Guld", bs: "Ukras", sq: "The Ornaments of Gold", pl: "The Ornaments of Gold", pt: "The Ornaments of Gold" },
  44: { en: "The Smoke", ur: "دھواں", tr: "Duhân", bn: "ধোঁয়া", zh: "烟雾", fr: "La fumée", fa: "The Smoke", ru: "Дым", kk: "The Smoke", de: "The Smoke", es: "El Humo", nl: "De Rook", it: "Il Fumo", sv: "Rök", bs: "Dim", sq: "The Smoke", pl: "The Smoke", pt: "The Smoke" },
  45: { en: "The Crouching", ur: "زانوٗوں کے بل گری ہوئی", tr: "Câsiye", bn: "নতজানু", zh: "屈膝", fr: "L'agenouillée", fa: "The Crouching", ru: "Коленопреклоненные", kk: "The Crouching", de: "The Crouching", es: "La Arrodillada", nl: "De Knielenden", it: "La Genuflessa", sv: "På Knä", bs: "Oni koji kleče", sq: "The Crouching", pl: "The Crouching", pt: "The Crouching" },
  46: { en: "The Wind-Curved Sandhills", ur: "ریگستان", tr: "Ahkâf", bn: "বালুর পাহাড়", zh: "沙丘", fr: "Al-Ahqaf", fa: "The Wind-Curved Sandhills", ru: "Барханы", kk: "The Wind-Curved Sandhills", de: "The Wind-Curved Sandhills", es: "Las Dunas", nl: "De Gebogen Duinen", it: "Al-Ahqрf", sv: "Sanddynorna", bs: "Ahkaf", sq: "The Wind-Curved Sandhills", pl: "The Wind-Curved Sandhills", pt: "The Wind-Curved Sandhills" },
  47: { en: "Muhammad", ur: "محمدﷺ", tr: "Muhammed", bn: "নবী মুহাম্মদ", zh: "穆罕默德", fr: "Mouhammad", fa: "Muhammad", ru: "Мухаммад", kk: "Muhammad", de: "Muhammad", es: "Muhammad", nl: "Mohammed", it: "Muhammad", sv: "Muhammad", bs: "Muhammed", sq: "Muhammad", pl: "Muhammad", pt: "Muhammad" },
  48: { en: "The Victory", ur: "فتح", tr: "Fetih", bn: "বিজয়", zh: "胜利", fr: "La victoire éclatante", fa: "The Victory", ru: "Победа", kk: "The Victory", de: "The Victory", es: "La Victoria", nl: "De Overwinning", it: "La Vittoria", sv: "Segern", bs: "Pobjeda", sq: "The Victory", pl: "The Victory", pt: "The Victory" },
  49: { en: "The Rooms", ur: "حجرے", tr: "Hucurât", bn: "আবাস", zh: "寝室", fr: "Les appartements", fa: "The Rooms", ru: "Комнаты", kk: "The Rooms", de: "The Rooms", es: "Los Aposentos Privados", nl: "De Binnenkamers", it: "Le Stanze Intime", sv: "De Inre Rummen", bs: "Sobe", sq: "The Rooms", pl: "The Rooms", pt: "The Rooms" },
  50: { en: "The Letter \"Qaf\"", ur: "قٓ", tr: "Kâf", bn: "কাফ", zh: "戛弗", fr: "Qaf", fa: "The Letter \"Qaf\"", ru: "Каф", kk: "The Letter \"Qaf\"", de: "The Letter \"Qaf\"", es: "Qaf", nl: "Qaaf (de letter)", it: "Qтf", sv: "Qaf", bs: "Kaf", sq: "The Letter \"Qaf\"", pl: "The Letter \"Qaf\"", pt: "The Letter \"Qaf\"" },
  51: { en: "The Winnowing Winds", ur: "بکھیرنے والیاں", tr: "Zâriyât", bn: "বিক্ষেপকারী বাতাস", zh: "播种者", fr: "Qui éparpillent", fa: "The Winnowing Winds", ru: "Рассеивающие прах", kk: "The Winnowing Winds", de: "The Winnowing Winds", es: "Los Que Levantan un Torbellino", nl: "De Winden die doen opwaaien", it: "Quelle che spargono", sv: "De Som Virvlar Upp", bs: "Oni koji pûšū", sq: "The Winnowing Winds", pl: "The Winnowing Winds", pt: "The Winnowing Winds" },
  52: { en: "The Mount", ur: "طور پہاڑ", tr: "Tûr", bn: "পাহাড়", zh: "山岳", fr: "Le mont At-Tour", fa: "The Mount", ru: "Гора", kk: "The Mount", de: "The Mount", es: "El Monte", nl: "De Berg", it: "Il Monte", sv: "Sinai Berg", bs: "Gora", sq: "The Mount", pl: "The Mount", pt: "The Mount" },
  53: { en: "The Star", ur: "ستارہ", tr: "Necm", bn: "তারা", zh: "星宿", fr: "L'étoile", fa: "The Star", ru: "Звезда", kk: "The Star", de: "The Star", es: "El Astro", nl: "De Ster", it: "La Stella", sv: "Stjärnan", bs: "Zvijezda", sq: "The Star", pl: "The Star", pt: "The Star" },
  54: { en: "The Moon", ur: "چاند", tr: "Kamer", bn: "চাঁদ", zh: "月亮", fr: "La lune", fa: "The Moon", ru: "Месяц", kk: "The Moon", de: "The Moon", es: "La Luna", nl: "De Maan", it: "La Luna", sv: "Månen", bs: "Mjesec", sq: "The Moon", pl: "The Moon", pt: "The Moon" },
  55: { en: "The Beneficent", ur: "مہربان", tr: "Rahmân", bn: "পরম করুণাময়", zh: "至仁主", fr: "Le Tout Miséricordieux", fa: "The Beneficent", ru: "Милостивый", kk: "The Beneficent", de: "The Beneficent", es: "El Misericordioso", nl: "De Erbarmer", it: "Il Compassionevole", sv: "Den Nåderike", bs: "Milostivi", sq: "The Beneficent", pl: "The Beneficent", pt: "The Beneficent" },
  56: { en: "The Inevitable", ur: "واقعہ ہونے والی قیامت", tr: "Vâkıa", bn: "নিশ্চিত ঘটনা", zh: "大事", fr: "L'inévitable", fa: "The Inevitable", ru: "Событие", kk: "The Inevitable", de: "The Inevitable", es: "Lo Que ha de Ocurrir", nl: "De Dag der Opstanding", it: "L'Evento", sv: "Det Som Måste Komma", bs: "Događaj", sq: "The Inevitable", pl: "The Inevitable", pt: "The Inevitable" },
  57: { en: "The Iron", ur: "فولاد", tr: "Hadîd", bn: "লোহা", zh: "铁", fr: "Le fer", fa: "The Iron", ru: "Железо", kk: "The Iron", de: "The Iron", es: "El Hierro", nl: "Het Ijzer", it: "Il Ferro", sv: "Järnet", bs: "Gvožđe", sq: "The Iron", pl: "The Iron", pt: "The Iron" },
  58: { en: "The Pleading Woman", ur: "جھگڑنے والی", tr: "Mücâdele", bn: "অনুযোগকারিণী", zh: "辩诉者", fr: "La discussion", fa: "The Pleading Woman", ru: "Препирающаяся", kk: "The Pleading Woman", de: "The Pleading Woman", es: "La Discusión", nl: "Zij die Twistte", it: "La Disputante", sv: "Hon Som Vädjar", bs: "Rasprava", sq: "The Pleading Woman", pl: "The Pleading Woman", pt: "The Pleading Woman" },
  59: { en: "The Exile", ur: "حشر", tr: "Haşr", bn: "সমাবেশ", zh: "放逐", fr: "L'exode", fa: "The Exile", ru: "Сбор", kk: "The Exile", de: "The Exile", es: "La Concentración", nl: "De Verzameling", it: "L'Esodo", sv: "Mönstringen", bs: "Progonstvo", sq: "The Exile", pl: "The Exile", pt: "The Exile" },
  60: { en: "She that is to be examined", ur: "امتحان لی جانے والی", tr: "Mümtehine", bn: "নারী, যাকে পরীক্ষা করা হবে", zh: "受考验的妇人", fr: "L'éprouvée", fa: "She that is to be examined", ru: "Испытуемая", kk: "She that is to be examined", de: "She that is to be examined", es: "La Examinada", nl: "De ondervraagde Vrouwen", it: "L'Esaminata", sv: "Den Som Skall Förhöras", bs: "Provjerena", sq: "She that is to be examined", pl: "She that is to be examined", pt: "She that is to be examined" },
  61: { en: "The Ranks", ur: "صف", tr: "Saf", bn: "সারিবদ্ধ সৈন্যদল", zh: "列阵", fr: "Le rang", fa: "The Ranks", ru: "Ряды", kk: "The Ranks", de: "The Ranks", es: "La Fila", nl: "De Slagorde", it: "I Ranghi Serrati", sv: "I Slutna Led", bs: "Bojni red", sq: "The Ranks", pl: "The Ranks", pt: "The Ranks" },
  62: { en: "The Congregation, Friday", ur: "جمعہ", tr: "Cuma", bn: "সম্মেলন/শুক্রবার", zh: "聚礼", fr: "Le vendredi", fa: "The Congregation, Friday", ru: "Собрание", kk: "The Congregation, Friday", de: "The Congregation, Friday", es: "El Viernes", nl: "Vrijdag", it: "Il Venerdь", sv: "Fredagsbönen", bs: "Petak", sq: "The Congregation, Friday", pl: "The Congregation, Friday", pt: "The Congregation, Friday" },
  63: { en: "The Hypocrites", ur: "منافقین", tr: "Münâfikûn", bn: "ভণ্ড বিশ্বাসী", zh: "伪信者", fr: "Les hypocrites", fa: "The Hypocrites", ru: "Лицемеры", kk: "The Hypocrites", de: "The Hypocrites", es: "Los Hipócritas", nl: "De Hypocrieten", it: "Gli Ipocriti", sv: "Hycklarna", bs: "Licemjeri", sq: "The Hypocrites", pl: "The Hypocrites", pt: "The Hypocrites" },
  64: { en: "The Mutual Disillusion", ur: "ہار جیت", tr: "Tegâbün", bn: "মোহ অপসারণ", zh: "相欺", fr: "La grande perte", fa: "The Mutual Disillusion", ru: "Взаимное обделение", kk: "The Mutual Disillusion", de: "The Mutual Disillusion", es: "El Desengaño", nl: "Beider Verlies en Winst", it: "Il Reciproco Inganno", sv: "Då Vinnarna Och Förlorarna Byter Plats", bs: "Samoobmana", sq: "The Mutual Disillusion", pl: "The Mutual Disillusion", pt: "The Mutual Disillusion" },
  65: { en: "The Divorce", ur: "طلاق", tr: "Talâk", bn: "তালাক", zh: "离婚", fr: "Le divorce", fa: "The Divorce", ru: "Развод", kk: "The Divorce", de: "The Divorce", es: "El Divorcio", nl: "De Scheiding", it: "Il Divorzio", sv: "Skilsmässa", bs: "Razvod braka", sq: "The Divorce", pl: "The Divorce", pt: "The Divorce" },
  66: { en: "The Prohibition", ur: "حرمت", tr: "Tahrîm", bn: "নিষিদ্ধকরণ", zh: "禁戒", fr: "L'interdiction", fa: "The Prohibition", ru: "Запрещение", kk: "The Prohibition", de: "The Prohibition", es: "La Prohibición", nl: "Het Verbod", it: "L'Interdizione", sv: "Förbudet", bs: "Zabrana", sq: "The Prohibition", pl: "The Prohibition", pt: "The Prohibition" },
  67: { en: "The Sovereignty", ur: "بادشاہ", tr: "Mülk", bn: "সার্বভৌম কর্তৃত্ব", zh: "国权", fr: "La royauté", fa: "The Sovereignty", ru: "Власть", kk: "The Sovereignty", de: "The Sovereignty", es: "La Soberanía", nl: "De Heerschappij", it: "La Sovranitр", sv: "Herravälde", bs: "Vlast", sq: "The Sovereignty", pl: "The Sovereignty", pt: "The Sovereignty" },
  68: { en: "The Pen", ur: "قلم", tr: "Kalem", bn: "কলম", zh: "笔", fr: "La plume", fa: "The Pen", ru: "Письменная трость", kk: "The Pen", de: "The Pen", es: "El Cálamo", nl: "De Pen", it: "Il Calamo", sv: "Pennan", bs: "Kalem", sq: "The Pen", pl: "The Pen", pt: "The Pen" },
  69: { en: "The Reality", ur: "حق ہونے والی", tr: "Hâkka", bn: "নিশ্চিত সত্য", zh: "真灾", fr: "L'inéluctable", fa: "The Reality", ru: "Неминуемое", kk: "The Reality", de: "The Reality", es: "La Verdad Indefectible", nl: "De Zekere Realiteit", it: "L'Inevitabile", sv: "Sanningens Stund", bs: "Čas neizbježni", sq: "The Reality", pl: "The Reality", pt: "The Reality" },
  70: { en: "The Ascending Stairways", ur: "عروج", tr: "Meâric", bn: "উন্নয়নের সোপান", zh: "天梯", fr: "Les voies d'ascension", fa: "The Ascending Stairways", ru: "Ступени", kk: "The Ascending Stairways", de: "The Ascending Stairways", es: "Los Grados de Elevación", nl: "De Opgaande Trappen", it: "Le Vie dell'Ascesa", sv: "Vägarna Upp Till Gud", bs: "Stepeni", sq: "The Ascending Stairways", pl: "The Ascending Stairways", pt: "The Ascending Stairways" },
  71: { en: "Noah", ur: "نوح", tr: "Nûh", bn: "নবী নূহ", zh: "努哈", fr: "Noé", fa: "Noah", ru: "Нух", kk: "Noah", de: "Noah", es: "Noé", nl: "Noah", it: "Noш", sv: "Noa", bs: "Nuh", sq: "Noah", pl: "Noah", pt: "Noah" },
  72: { en: "The Jinn", ur: "جن", tr: "Cin", bn: "জিন সম্প্রদায়", zh: "精灵", fr: "Les djinns", fa: "The Jinn", ru: "Джинны", kk: "The Jinn", de: "The Jinn", es: "Los Genios", nl: "De Djinn", it: "I Dшmoni", sv: "Osynliga Väsen", bs: "Džinni", sq: "The Jinn", pl: "The Jinn", pt: "The Jinn" },
  73: { en: "The Enshrouded One", ur: "کپڑا لپیٹنے والا", tr: "Müzzemmil", bn: "বস্ত্রাচ্ছাদনকারী", zh: "披衣的人", fr: "L'enveloppé", fa: "The Enshrouded One", ru: "Закутавшийся", kk: "The Enshrouded One", de: "The Enshrouded One", es: "El Envuelto en El Manto", nl: "De Omhulde", it: "L'avvolto", sv: "Du Som Täcker Över Dig", bs: "Umotani", sq: "The Enshrouded One", pl: "The Enshrouded One", pt: "The Enshrouded One" },
  74: { en: "The Cloaked One", ur: "کپڑا اوڑھنے والا", tr: "Müddessir", bn: "পোশাক পরিহিত", zh: "盖被的人", fr: "Celui qui se couvre", fa: "The Cloaked One", ru: "Завернувшийся", kk: "The Cloaked One", de: "The Cloaked One", es: "El Arropado", nl: "De Ommantelde", it: "L'Avvolto nel Mantello", sv: "Du Som Sveper In Dig", bs: "Pokriveni", sq: "The Cloaked One", pl: "The Cloaked One", pt: "The Cloaked One" },
  75: { en: "The Resurrection", ur: "قیامۃ", tr: "Kıyâmet", bn: "পুনরুত্থান", zh: "复活", fr: "La résurrection", fa: "The Resurrection", ru: "Воскресение", kk: "The Resurrection", de: "The Resurrection", es: "El Levantamiento", nl: "De Wederopstanding", it: "La Resurrezione", sv: "Uppståndelsen", bs: "Smak svijeta", sq: "The Resurrection", pl: "The Resurrection", pt: "The Resurrection" },
  76: { en: "The Man", ur: "انسان", tr: "İnsân", bn: "মানবজাতি", zh: "人", fr: "L'homme", fa: "The Man", ru: "Человек", kk: "The Man", de: "The Man", es: "El Hombre", nl: "De Mens", it: "L'Uomo", sv: "Människan", bs: "Vrijeme", sq: "The Man", pl: "The Man", pt: "The Man" },
  77: { en: "The Emissaries", ur: "بھیجی جانے والی ہوائیں", tr: "Mürselât", bn: "প্রেরিত পুরুষ", zh: "天使", fr: "Les envoyés", fa: "The Emissaries", ru: "Посылаемые", kk: "The Emissaries", de: "The Emissaries", es: "Los Que Son Enviados", nl: "De Uitgezondenen", it: "Le Inviate", sv: "De Som Sänds Ut", bs: "Poslani", sq: "The Emissaries", pl: "The Emissaries", pt: "The Emissaries" },
  78: { en: "The Tidings", ur: "خبر", tr: "Nebe", bn: "মহাসংবাদ", zh: "消息", fr: "La nouvelle", fa: "The Tidings", ru: "Весть", kk: "The Tidings", de: "The Tidings", es: "La Noticia", nl: "De Aankondiging", it: "L'Annuncio", sv: "Tillkännagivandet", bs: "Vijest", sq: "The Tidings", pl: "The Tidings", pt: "The Tidings" },
  79: { en: "Those who drag forth", ur: "زور سے کھینچنے والے", tr: "Naziât", bn: "প্রচেষ্টাকারী", zh: "急掣的", fr: "Ceux qui arrachent", fa: "Those who drag forth", ru: "Исторгающие", kk: "Those who drag forth", de: "Those who drag forth", es: "Los Que Arrancan", nl: "De Uitrukkenden", it: "Le Strappanti Violente", sv: "De Som Stiger Över Horisonten", bs: "Oni koji čupaju", sq: "Those who drag forth", pl: "Those who drag forth", pt: "Those who drag forth" },
  80: { en: "He Frowned", ur: "تیوری چڑہائی", tr: "Abese", bn: "সে ভ্রু কুঁচকালো", zh: "皱眉", fr: "Il s'est renfrogné", fa: "He Frowned", ru: "Нахмурился", kk: "He Frowned", de: "He Frowned", es: "Frunció El Ceño", nl: "Hij fronste", it: "Si Accigliђ", sv: "Med Bister Min", bs: "Namrštio se", sq: "He Frowned", pl: "He Frowned", pt: "He Frowned" },
  81: { en: "The Overthrowing", ur: "لپیٹنا", tr: "Tekvîr", bn: "অন্ধকারাচ্ছন্ন", zh: "黯黮", fr: "L'obscurcissement", fa: "The Overthrowing", ru: "Скручивание", kk: "The Overthrowing", de: "The Overthrowing", es: "El Arrollamiento", nl: "Het Oprollen", it: "L'Oscuramento", sv: "När Solen Lindas In", bs: "Prestanak sjaja", sq: "The Overthrowing", pl: "The Overthrowing", pt: "The Overthrowing" },
  82: { en: "The Cleaving", ur: "ٹکڑے ہونا", tr: "İnfitâr", bn: "বিদীর্ণ করা", zh: "破裂", fr: "La rupture", fa: "The Cleaving", ru: "Раскалывание", kk: "The Cleaving", de: "The Cleaving", es: "La Hendidura", nl: "Het Splijten", it: "Lo Squarciarsi", sv: "När Himlen Rämnar", bs: "Rascjepljenje", sq: "The Cleaving", pl: "The Cleaving", pt: "The Cleaving" },
  83: { en: "The Defrauding", ur: "ناپ تول میں کمی کرنے والے", tr: "Mutaffifîn", bn: "প্রতারণা করা", zh: "称量不公", fr: "Les fraudeurs", fa: "The Defrauding", ru: "Обвешивающие", kk: "The Defrauding", de: "The Defrauding", es: "Los Defraudadores", nl: "De Zwendelaars", it: "I Frodatori", sv: "De Som Snålar Med Mått Och Vikt", bs: "Oni koji pri mjerenju zakidaju", sq: "The Defrauding", pl: "The Defrauding", pt: "The Defrauding" },
  84: { en: "The Sundering", ur: "پھٹنا", tr: "İnşikâk", bn: "খণ্ড-বিখণ্ডকরণ", zh: "绽裂", fr: "La déchirure", fa: "The Sundering", ru: "Разверзнется", kk: "The Sundering", de: "The Sundering", es: "El Resquebrajamiento", nl: "Het Verscheuren", it: "La Fenditura", sv: "När Himlen Brister I Stycken", bs: "Cijepanje", sq: "The Sundering", pl: "The Sundering", pt: "The Sundering" },
  85: { en: "The Mansions of the Stars", ur: "برج", tr: "Burûc", bn: "নক্ষত্রপুঞ্জ", zh: "十二宫", fr: "Les constellations", fa: "The Mansions of the Stars", ru: "Созвездия Зодиака", kk: "The Mansions of the Stars", de: "The Mansions of the Stars", es: "Las Constelaciones", nl: "De Sterrenstelsels", it: "Le Costellazioni", sv: "Stjärnbilderna", bs: "Sazviježđa", sq: "The Mansions of the Stars", pl: "The Mansions of the Stars", pt: "The Mansions of the Stars" },
  86: { en: "The Nightcommer", ur: "رات کو آنے والا", tr: "Târık", bn: "রাতের আগন্তুক", zh: "启明星", fr: "L'astre nocturne", fa: "The Nightcommer", ru: "Ночной путник", kk: "The Nightcommer", de: "The Nightcommer", es: "El Que Viene de Noche", nl: "De Verlichtende Ster", it: "L'Astro Notturno", sv: "Den Nattliga Besökaren", bs: "Danica", sq: "The Nightcommer", pl: "The Nightcommer", pt: "The Nightcommer" },
  87: { en: "The Most High", ur: "اعلی", tr: "A'lâ", bn: "সর্বোন্নত", zh: "至尊", fr: "Le Très-Haut", fa: "The Most High", ru: "Всевышний", kk: "The Most High", de: "The Most High", es: "El Altísimo", nl: "De Hoogste", it: "L'Altissimo", sv: "Den Högste", bs: "Svevišnji", sq: "The Most High", pl: "The Most High", pt: "The Most High" },
  88: { en: "The Overwhelming", ur: "چھا جانے والی", tr: "Gâşiye", bn: "বিহ্বলকর ঘটনা", zh: "大灾", fr: "L'enveloppante", fa: "The Overwhelming", ru: "Покрывающее", kk: "The Overwhelming", de: "The Overwhelming", es: "El Envolvente", nl: "De Overweldigende Gebeurtenis", it: "L'Avvolgente", sv: "Det Som Skall Överskugga Allt", bs: "Teška nevolja", sq: "The Overwhelming", pl: "The Overwhelming", pt: "The Overwhelming" },
  89: { en: "The Dawn", ur: "فجر", tr: "Fecr", bn: "ভোরবেলা", zh: "黎明", fr: "L'aube", fa: "The Dawn", ru: "Заря", kk: "The Dawn", de: "The Dawn", es: "La Aurora", nl: "De Dageraad", it: "L'Alba", sv: "Gryningsljuset", bs: "Zora", sq: "The Dawn", pl: "The Dawn", pt: "The Dawn" },
  90: { en: "The City", ur: "شہر", tr: "Beled", bn: "নগর", zh: "地方", fr: "La cité", fa: "The City", ru: "Город", kk: "The City", de: "The City", es: "El Territorio", nl: "De Stad", it: "La Contrada", sv: "Landet", bs: "Grad", sq: "The City", pl: "The City", pt: "The City" },
  91: { en: "The Sun", ur: "آفتاب", tr: "Şems", bn: "সূর্য", zh: "太阳", fr: "Le soleil", fa: "The Sun", ru: "Солнце", kk: "The Sun", de: "The Sun", es: "El Sol", nl: "De Zon", it: "Il Sole", sv: "Solen", bs: "Sunce", sq: "The Sun", pl: "The Sun", pt: "The Sun" },
  92: { en: "The Night", ur: "رات", tr: "Leyl", bn: "রাত", zh: "黑夜", fr: "La nuit", fa: "The Night", ru: "Ночь", kk: "The Night", de: "The Night", es: "La Noche", nl: "De Nacht", it: "La Notte", sv: "Natten", bs: "Noć", sq: "The Night", pl: "The Night", pt: "The Night" },
  93: { en: "The Morning Hours", ur: "دن کا چڑھنا", tr: "Duhâ", bn: "পূর্বাহ্নের সুর্যকিরণ", zh: "上午", fr: "Le jour montant", fa: "The Morning Hours", ru: "Утро", kk: "The Morning Hours", de: "The Morning Hours", es: "La Claridad de La Mañana", nl: "Het Ochtendlicht", it: "La Luce del Mattino", sv: "Det Klara Morgonljuset", bs: "Jutro", sq: "The Morning Hours", pl: "The Morning Hours", pt: "The Morning Hours" },
  94: { en: "The Relief", ur: "تسکین", tr: "İnşirâh", bn: "বক্ষ প্রশস্তকরণ", zh: "开拓", fr: "L'ouverture", fa: "The Relief", ru: "Раскрытие", kk: "The Relief", de: "The Relief", es: "No Te Hemos Abierto", nl: "De Verruiming", it: "L'Apertura", sv: "Har Vi Inte Öppnat Ditt Bröst", bs: "Širokogrudnost", sq: "The Relief", pl: "The Relief", pt: "The Relief" },
  95: { en: "The Fig", ur: "انجیر", tr: "Tîn", bn: "ডুমুর", zh: "无花果", fr: "Les figues", fa: "The Fig", ru: "Смоковница", kk: "The Fig", de: "The Fig", es: "Los Higos", nl: "De Vijg", it: "Il Fico", sv: "Fikonträdet", bs: "Smokva", sq: "The Fig", pl: "The Fig", pt: "The Fig" },
  96: { en: "The Clot", ur: "جما ہوا خون", tr: "Alak", bn: "রক্তপিণ্ড", zh: "血块", fr: "L'adhérence", fa: "The Clot", ru: "Сгусток крови", kk: "The Clot", de: "The Clot", es: "El Coágulo", nl: "De Bloedklomp", it: "L'Aderenza", sv: "Grodden", bs: "Ugrušak", sq: "The Clot", pl: "The Clot", pt: "The Clot" },
  97: { en: "The Power", ur: "شب قدر", tr: "Kadir", bn: "মহিমান্বিত", zh: "高贵", fr: "La destinée", fa: "The Power", ru: "Предопределение", kk: "The Power", de: "The Power", es: "El Decreto", nl: "De Waardevolle Nacht", it: "Il Destino", sv: "Allmaktens Natt", bs: "Noć Kadr", sq: "The Power", pl: "The Power", pt: "The Power" },
  98: { en: "The Clear Proof", ur: "ثبوت", tr: "Beyyine", bn: "প্রমাণ", zh: "明证", fr: "La preuve", fa: "The Clear Proof", ru: "Ясное знамение", kk: "The Clear Proof", de: "The Clear Proof", es: "La Evidencia", nl: "Het Duidelijke Bewijs", it: "La prova", sv: "Det Klara Vittnesbördet", bs: "Dokaz jasni", sq: "The Clear Proof", pl: "The Clear Proof", pt: "The Clear Proof" },
  99: { en: "The Earthquake", ur: "زلزلہ", tr: "Zilzâl", bn: "ভূমিকম্প", zh: "地震", fr: "Le séisme", fa: "The Earthquake", ru: "Сотрясение", kk: "The Earthquake", de: "The Earthquake", es: "El Temblor", nl: "De Aardbeving", it: "Il Terremoto", sv: "När Jorden Skälver", bs: "Zemljotres", sq: "The Earthquake", pl: "The Earthquake", pt: "The Earthquake" },
  100: { en: "The Courser", ur: "دوڑنے والے گھوڑے", tr: "Âdiyât", bn: "অভিযানকারী", zh: "奔驰的马队", fr: "Les coursiers", fa: "The Courser", ru: "Скачущие", kk: "The Courser", de: "The Courser", es: "Los Que Galopan", nl: "De Voortrennenden", it: "Le Scalpitanti", sv: "Stridshästarna", bs: "Oni koji jure", sq: "The Courser", pl: "The Courser", pt: "The Courser" },
  101: { en: "The Calamity", ur: "کھڑکھڑاہٹ", tr: "Kâria", bn: "মহাসংকট", zh: "大难", fr: "Le fracas", fa: "The Calamity", ru: "Великое бедствие", kk: "The Calamity", de: "The Calamity", es: "La Conmoción", nl: "De Daverende", it: "La Percotente", sv: "Det Dundrande Slaget", bs: "Smak svijeta", sq: "The Calamity", pl: "The Calamity", pt: "The Calamity" },
  102: { en: "The Rivalry in world increase", ur: "کثرت", tr: "Tekâsür", bn: "প্রাচুর্যের প্রতিযোগিতা", zh: "竞赛富遮", fr: "La course aux richesses", fa: "The Rivalry in world increase", ru: "Страсть к приумножению", kk: "The Rivalry in world increase", de: "The Rivalry in world increase", es: "La Rivalidad", nl: "De Wedijver om Meer", it: "Il Rivaleggiare", sv: "Tävlan I Rikedom", bs: "Nadmetanje", sq: "The Rivalry in world increase", pl: "The Rivalry in world increase", pt: "The Rivalry in world increase" },
  103: { en: "The Declining Day", ur: "زمانہ", tr: "Asr", bn: "সময়", zh: "时光", fr: "Le temps", fa: "The Declining Day", ru: "Предвечернее время", kk: "The Declining Day", de: "The Declining Day", es: "El Tiempo", nl: "De Tijd", it: "Il Tempo", sv: "Den Flyende Tiden", bs: "Vrijeme", sq: "The Declining Day", pl: "The Declining Day", pt: "The Declining Day" },
  104: { en: "The Traducer", ur: "عیب لگانے والا", tr: "Hümeze", bn: "পরনিন্দাকারী", zh: "诽谤者", fr: "Les calomniateurs", fa: "The Traducer", ru: "Хулитель", kk: "The Traducer", de: "The Traducer", es: "El Murmurador", nl: "De Lasteraar", it: "Il Diffamatore", sv: "Baktalaren", bs: "Klevetnik", sq: "The Traducer", pl: "The Traducer", pt: "The Traducer" },
  105: { en: "The Elephant", ur: "ہاتھی", tr: "Fîl", bn: "হাতি", zh: "象", fr: "L'éléphant", fa: "The Elephant", ru: "Слон", kk: "The Elephant", de: "The Elephant", es: "El Elefante", nl: "De Olifant", it: "L'Elefante", sv: "Elefanten", bs: "Slon", sq: "The Elephant", pl: "The Elephant", pt: "The Elephant" },
  106: { en: "Quraysh", ur: "قریش", tr: "Kureyş", bn: "কুরাইশ গোত্র", zh: "古来氏", fr: "Les Quraysh", fa: "Quraysh", ru: "Курейшиты", kk: "Quraysh", de: "Quraysh", es: "Los Quraysh", nl: "De Quraysh", it: "I Coreisciti", sv: "Quraysh", bs: "Kurejšije", sq: "Quraysh", pl: "Quraysh", pt: "Quraysh" },
  107: { en: "The Small kindnesses", ur: "تھوڑی سی چیز", tr: "Maûn", bn: "সাহায্য সহায়তা", zh: "什物", fr: "L'entraide", fa: "The Small kindnesses", ru: "Мелочь", kk: "The Small kindnesses", de: "The Small kindnesses", es: "La Ayuda Imprescindible", nl: "De Levensbenodigdheden", it: "L'Utensile", sv: "Den Minsta Hjälp", bs: "Davanje u naruč", sq: "The Small kindnesses", pl: "The Small kindnesses", pt: "The Small kindnesses" },
  108: { en: "The Abundance", ur: "جنت کی نہر", tr: "Kevser", bn: "কাউসার/প্রাচুর্য", zh: "多福", fr: "L'abondance", fa: "The Abundance", ru: "Изобилие", kk: "The Abundance", de: "The Abundance", es: "La Abundancia", nl: "De Overvloed", it: "L'Abbondanza", sv: "Det Goda I Överflöd", bs: "Mnogō dobro", sq: "The Abundance", pl: "The Abundance", pt: "The Abundance" },
  109: { en: "The Disbelievers", ur: "کافرین", tr: "Kâfirûn", bn: "অবিশ্বাসী", zh: "不信道的人们", fr: "Les mécréants", fa: "The Disbelievers", ru: "Неверующие", kk: "The Disbelievers", de: "The Disbelievers", es: "Los Incrédulos", nl: "De Ongelovigen", it: "Miscredenti", sv: "Sanningens Förnekare", bs: "Nevjernici", sq: "The Disbelievers", pl: "The Disbelievers", pt: "The Disbelievers" },
  110: { en: "The Divine Support", ur: "نصرت", tr: "Nasr", bn: "সাহায্য", zh: "援助", fr: "Le secours", fa: "The Divine Support", ru: "Помощь", kk: "The Divine Support", de: "The Divine Support", es: "La Victoria", nl: "De Hulp", it: "L'Ausilio", sv: "Guds Hjälp", bs: "Pomoć", sq: "The Divine Support", pl: "The Divine Support", pt: "The Divine Support" },
  111: { en: "The Palm Fiber", ur: "خوب بٹی ہوئی", tr: "Tebbet", bn: "খেজুরের পাকানো (রশি)", zh: "火焰", fr: "Les fibres", fa: "The Palm Fiber", ru: "Пальмовые волокна", kk: "The Palm Fiber", de: "The Palm Fiber", es: "La Fibra", nl: "De Palmvezel", it: "Le Fibre di Palma", sv: "Ett Tvinnat Rep", bs: "Plamen", sq: "The Palm Fiber", pl: "The Palm Fiber", pt: "The Palm Fiber" },
  112: { en: "The Sincerity", ur: "اخلاص", tr: "İhlâs", bn: "আন্তরিকতা", zh: "忠诚", fr: "La sincérité", fa: "The Sincerity", ru: "Очищение веры", kk: "The Sincerity", de: "The Sincerity", es: "La Adoración Pura", nl: "Het Zuivere Geloof", it: "Il Puro Monoteismo", sv: "Den Rena Tron", bs: "Iskrenost", sq: "The Sincerity", pl: "The Sincerity", pt: "The Sincerity" },
  113: { en: "The Daybreak", ur: "صبح", tr: "Felak", bn: "নিশিভোর", zh: "曙光", fr: "L'aube naissante", fa: "The Daybreak", ru: "Рассвет", kk: "The Daybreak", de: "The Daybreak", es: "El Rayar del Alba", nl: "De Ochtendschemering", it: "L'Alba Nascente", sv: "Gryningens Herre", bs: "Svitanje", sq: "The Daybreak", pl: "The Daybreak", pt: "The Daybreak" },
  114: { en: "Mankind", ur: "انسان", tr: "Nâs", bn: "মানুষ জাতি", zh: "世人", fr: "Les humains", fa: "Mankind", ru: "Люди", kk: "Mankind", de: "Mankind", es: "Los Hombres", nl: "De Mensheid", it: "Gli Uomini", sv: "Människornas Herre", bs: "Ljudi", sq: "Mankind", pl: "Mankind", pt: "Mankind" },
};

/** Localized surah name for a language code, falling back to English then number. */
export function surahNameInLang(surahNumber: number, lang: string): string | undefined {
  const row = SURAH_NAMES_BY_LANG[surahNumber];
  if (!row) return undefined;
  return row[lang] ?? row.en;
}

/**
 * Localized name ONLY when the language has a genuine translation. Some languages
 * (fa, de, kk, sq, pl, pt) aren't translated in the source data and silently
 * return the English name — for those this returns null so callers can fall back
 * to the Arabic-script name instead of showing English in place of the local one.
 */
export function distinctSurahName(surahNumber: number, lang: string): string | null {
  const row = SURAH_NAMES_BY_LANG[surahNumber];
  if (!row || lang === 'en') return null; // English → keep decorative Arabic-script name
  const loc = row[lang];
  if (!loc || loc === row.en) return null;
  return loc;
}
